Stride Reference Manual: stride::ContactPoolType::IdSubscriptArray< bool > Class Template Reference
stride::ContactPoolType::IdSubscriptArray< bool > Class Template Reference
Specialisation of IdSubscriptArray foor booleans.
#include <IdSubscriptArray.h>
Public Member Functions
IdSubscriptArray (bool t=bool())
What we 'll use most often and where we can have a default and initialize all array elements to the same value.
IdSubscriptArray (std::initializer_list< bool > l)
When we want to use an initializer list the elements is the (possibly emty) initializer list are applied to the first elements in order; any remaininig elements are default initialized.
std::bitset< NumOfTypes()>::reference operator[] (ContactPoolType::Id id)
Subscripting with pool typ id as argument.
bool operator[] (ContactPoolType::Id id) const
Subscripting with pool typ id as argument.
bitset< NumOfTypes()>::reference at (ContactPoolType::Id id)
Subscripting with pool typ id as argument.
bool at (ContactPoolType::Id id) const
Subscripting with pool typ id as argument.
Detailed Description
template<>
class stride::ContactPoolType::IdSubscriptArray< bool >
Specialisation of IdSubscriptArray foor booleans.
Definition at line 120 of file IdSubscriptArray.h.
Constructor & Destructor Documentation
IdSubscriptArray() [1/2]
stride::ContactPoolType::IdSubscriptArray< bool >::IdSubscriptArray (bool t = bool()) inline explicit
What we 'll use most often and where we can have a default and initialize all array elements to the same value.
e.g. IdSubscriptArray<bool> m(true);
Definition at line 126 of file IdSubscriptArray.h.
IdSubscriptArray() [2/2]
stride::ContactPoolType::IdSubscriptArray< bool >::IdSubscriptArray (std::initializer_list< bool > l) inline
When we want to use an initializer list the elements is the (possibly emty) initializer list are applied to the first elements in order; any remaininig elements are default initialized.
e.g. IdSubscriptArray<bool> mm {true, false, true};
Definition at line 138 of file IdSubscriptArray.h.
References stride::ContactPoolType::IdList, and stride::ContactPoolType::IdSubscriptArray< T >::operator[]().
Member Function Documentation
operator[]() [1/2]
std::bitset<NumOfTypes()>::reference stride::ContactPoolType::IdSubscriptArray< bool >::operator[] (ContactPoolType::Id id) inline
Subscripting with pool typ id as argument.
Definition at line 152 of file IdSubscriptArray.h.
References stride::ContactPoolType::ToSizeT().
operator[]() [2/2]
bool stride::ContactPoolType::IdSubscriptArray< bool >::operator[] (ContactPoolType::Id id) const inline
Subscripting with pool typ id as argument.
Definition at line 158 of file IdSubscriptArray.h.
References stride::ContactPoolType::ToSizeT().
at() [1/2]
bitset<NumOfTypes()>::reference stride::ContactPoolType::IdSubscriptArray< bool >::at (ContactPoolType::Id id) inline
Subscripting with pool typ id as argument.
Definition at line 164 of file IdSubscriptArray.h.
References stride::ContactPoolType::NumOfTypes(), and stride::ContactPoolType::ToSizeT().
at() [2/2]
bool stride::ContactPoolType::IdSubscriptArray< bool >::at (ContactPoolType::Id id) const inline
Subscripting with pool typ id as argument.
Definition at line 173 of file IdSubscriptArray.h.
References stride::ContactPoolType::NumOfTypes(), and stride::ContactPoolType::ToSizeT().
The documentation for this class was generated from the following file:
IdSubscriptArray.h