Stride Reference Manual: stride::util::CSVRow Class Reference
stride::util::CSVRow Class Reference
Row in CSV file.
#include <CSVRow.h>
Public Member Functions
CSVRow (const CSV *parent, const std::vector< std::string > &values)
CSVRow initialized with values. Should no be called by user code. CSV has convenience functions.
template<typename T = std::string>
T GetValue (size_t index) const
Get value at index. When T is specified, StringUtils are used to try to convert the value to type T.
template<typename T = std::string>
T GetValue (const std::string &label) const
Get value based on label. Note this is slower than using the index.
bool operator== (const CSVRow &other) const
Compare operator.
template<>
std::string GetValue (size_t index) const
Declaration of specialization.
template<>
std::string GetValue (const std::string &label) const
Declaration of specialization.
Protected Attributes
const CSV * m_parent
std::vector< std::string > m_values
Friends
std::ostream & operator<< (std::ostream &os, const CSVRow &row)
Print to stream.
Detailed Description
Row in CSV file.
Definition at line 35 of file CSVRow.h.
Constructor & Destructor Documentation
CSVRow()
stride::util::CSVRow::CSVRow (const CSV * parent, const std::vector< std::string > & values)
CSVRow initialized with values. Should no be called by user code. CSV has convenience functions.
Definition at line 38 of file CSVRow.cpp.
References stride::util::CSV::GetColumnCount(), m_values, stride::util::ToString(), and stride::util::Trim().
Member Function Documentation
GetValue() [1/4]
template<typename T > T stride::util::CSVRow::GetValue (size_t index) const inline
Get value at index. When T is specified, StringUtils are used to try to convert the value to type T.
Definition at line 70 of file CSVRow.h.
GetValue() [2/4]
template<typename T > T stride::util::CSVRow::GetValue (const std::string & label) const inline
Get value based on label. Note this is slower than using the index.
Definition at line 77 of file CSVRow.h.
operator==()
bool stride::util::CSVRow::operator== (const CSVRow & other) const
Compare operator.
Definition at line 67 of file CSVRow.cpp.
References m_values.
GetValue() [3/4]
template<> std::string stride::util::CSVRow::GetValue (size_t index) const
Declaration of specialization.
GetValue() [4/4]
template<> std::string stride::util::CSVRow::GetValue (const std::string & label) const
Declaration of specialization.
Friends And Related Function Documentation
operator<<
std::ostream& operator<< (std::ostream & os, const CSVRow & row) friend
Print to stream.
Definition at line 69 of file CSVRow.cpp.
Member Data Documentation
m_parent
const CSV* stride::util::CSVRow::m_parent protected
Definition at line 56 of file CSVRow.h.
m_values
std::vector<std::string> stride::util::CSVRow::m_values protected
Definition at line 57 of file CSVRow.h.
Referenced by CSVRow(), stride::util::operator<<(), and operator==().
The documentation for this class was generated from the following files:
CSVRow.h
CSVRow.cpp