Stride Reference Manual: stride::qt::QSim Class Reference
stride::qt::QSim Class Reference
The gui for the stride simulation, is responsible for the following things:
#include <QSim.h>
Public Slots
void StartNewSim ()
Start a new simulation and get the config from QConfig.
void RunXDays ()
Run the simulation for x Days.
Public Member Functions
QSim (boost::property_tree::ptree config_run)
Constructor.
QSim (std::shared_ptr< GuiRunner > _runner, boost::property_tree::ptree config_run)
Constructor.
~QSim () override=default
Destructor.
void SetUp (boost::property_tree::ptree run)
Set up the QSim.
void LoadLog (std::string log)
Loads a log file in the gui.
void LoadDay (std::shared_ptr< Sim > sim)
Loads the day of a simulation in the gui.
void Exec ()
Execute the QSim: show the gui.
std::shared_ptr< Window > GetWindow ()
Get the gui window.
Private Attributes
std::shared_ptr< GuiRunner > runner
Pointer to the GuiRunner.
std::shared_ptr< Window > window
The main window in the gui.
QConfig qConfig
The configuration window in the gui.
QLineEdit * numDaysEdit
Input field for the user: how many days we should run the sim.
std::shared_ptr< Map > map
Pointer to the map.
std::shared_ptr< Stats > stats
Pointer to the statistics.
boost::property_tree::ptree config_run
Ptree with the configuration for the simulation.
Detailed Description
The gui for the stride simulation, is responsible for the following things:
Setting up the GUI (building the Map, setting up and linking buttons, ...)
Loading a day or log of the simulation and visualize it on the Map.
Start and set up a new simulation.
Definition at line 32 of file QSim.h.
Constructor & Destructor Documentation
QSim() [1/2]
stride::qt::QSim::QSim (boost::property_tree::ptree config_run)
Constructor.
Sets up the window.
Parameters
config_run The property tree that contains the configuration for the simulation.
Definition at line 10 of file QSim.cpp.
References stride::qt::QConfig::BuildForm(), config_run, qConfig, stride::qt::QConfig::SetConfig(), StartNewSim(), and window.
QSim() [2/2]
stride::qt::QSim::QSim (std::shared_ptr< GuiRunner > _runner, boost::property_tree::ptree config_run)
Constructor.
Sets up the window + integrates all the necessary information from the runner in the window.
Parameters
_runner The simulation runner.
config_run The property tree that contains the configuration for the simulation.
Definition at line 20 of file QSim.cpp.
References config_run, runner, and SetUp().
~QSim()
stride::qt::QSim::~QSim () override default
Destructor.
Member Function Documentation
SetUp()
void stride::qt::QSim::SetUp (boost::property_tree::ptree run)
Set up the QSim.
Is automatically called when invoking the second constructor. Can be manually called to set up the gui at a later time.
Parameters
config_run The property tree that contains the configuration for the simulation.
Definition at line 26 of file QSim.cpp.
References config_run, stride::util::FileSys::GetDataDir(), map, numDaysEdit, runner, RunXDays(), stats, and window.
Referenced by QSim(), and StartNewSim().
LoadLog()
void stride::qt::QSim::LoadLog (std::string log)
Loads a log file in the gui.
(used for postprocessing)
Parameters
log Path to the log file.
Definition at line 71 of file QSim.cpp.
References stride::util::FileSys::GetCurrentDir(), map, runner, and window.
Referenced by main().
LoadDay()
void stride::qt::QSim::LoadDay (std::shared_ptr< Sim > sim)
Loads the day of a simulation in the gui.
Parameters
sim The simulation.
Definition at line 79 of file QSim.cpp.
References map, runner, and window.
Exec()
void stride::qt::QSim::Exec ()
Execute the QSim: show the gui.
Returns
Exit code of the gui.
Definition at line 87 of file QSim.cpp.
References map, and window.
Referenced by main().
GetWindow()
std::shared_ptr<Window> stride::qt::QSim::GetWindow () inline
Get the gui window.
Returns
The window.
Definition at line 71 of file QSim.h.
References window.
StartNewSim
void stride::qt::QSim::StartNewSim () slot
Start a new simulation and get the config from QConfig.
This will also remove the current simulation.
Definition at line 93 of file QSim.cpp.
References config_run, stride::Population::Create(), stride::Population::CreateEmpty(), stride::qt::QConfig::GetPtree(), map, qConfig, runner, stride::qt::QConfig::SaveConfig(), SetUp(), stride::qt::QConfig::UpdateForm(), and window.
Referenced by QSim().
RunXDays
void stride::qt::QSim::RunXDays () slot
Run the simulation for x Days.
Definition at line 126 of file QSim.cpp.
References numDaysEdit, and runner.
Referenced by SetUp().
Member Data Documentation
runner
std::shared_ptr<GuiRunner> stride::qt::QSim::runner private
Pointer to the GuiRunner.
Definition at line 83 of file QSim.h.
Referenced by LoadDay(), LoadLog(), QSim(), RunXDays(), SetUp(), and StartNewSim().
window
std::shared_ptr<Window> stride::qt::QSim::window private
The main window in the gui.
Definition at line 85 of file QSim.h.
Referenced by Exec(), GetWindow(), LoadDay(), LoadLog(), QSim(), SetUp(), and StartNewSim().
qConfig
QConfig stride::qt::QSim::qConfig private
The configuration window in the gui.
Definition at line 86 of file QSim.h.
Referenced by QSim(), and StartNewSim().
numDaysEdit
QLineEdit* stride::qt::QSim::numDaysEdit private
Input field for the user: how many days we should run the sim.
Definition at line 87 of file QSim.h.
Referenced by RunXDays(), and SetUp().
map
std::shared_ptr<Map> stride::qt::QSim::map private
Pointer to the map.
Definition at line 89 of file QSim.h.
Referenced by Exec(), LoadDay(), LoadLog(), SetUp(), and StartNewSim().
stats
std::shared_ptr<Stats> stride::qt::QSim::stats private
Pointer to the statistics.
Definition at line 91 of file QSim.h.
Referenced by SetUp().
config_run
boost::property_tree::ptree stride::qt::QSim::config_run private
Ptree with the configuration for the simulation.
Definition at line 92 of file QSim.h.
Referenced by QSim(), SetUp(), and StartNewSim().
The documentation for this class was generated from the following files:
QSim.h
QSim.cpp