Stride Reference Manual: stride Namespace Reference
stride Namespace Reference
Main namespace for the project.
Namespaces
ContactLogMode
Enum specifiying the level of logging required:
ContactPoolType
Namespace to manage types of ContactPool.
GridPoolType
output
Utilities for the output files.
qt
qttool
RNEngineType
Namespace to manage types of random engines.
sim_event
Namespace to manage events signalled by the SimRunner.
util
Utilities for the project.
viewers
Namespace for MVC-viewers that may be registered with SimRunner.
Classes
class AgeContactProfile
Contact rates as a function of age.
class Belief
Base class for all belief policies.
class BeliefSeeder
Seeds the population with Health data.
class Calendar
Class that keeps track of the 'state' of simulated world.
class CliController
Controls a simulation run initiated with the command line interface (cli).
class ContactHandler
Processes the contacts between persons and determines whether transmission occurs.
class ContactPool
Represents a group of Persons that potentially have contacts.
class DaysOffAll
No days off work or school.
class DaysOffInterface
Interface definition.
class DaysOffNone
No days off work or school.
class DaysOffSchool
Schools closed.
class DaysOffStandard
Standard situation for days off from work and school.
class DiseaseSeeder
Seeds population w.r.t immunity (natural immunity, vaccination, ...) and infection.
class GeoGrid
class GeoGridBuilder
class GeoGridPopulator
class GuiController
class GuiRunner
The simulation runner for the gui, inherits SimRunner.
class HBM
class Health
Holds a person's health data.
class HealthSeeder
Seeds the population with Health data.
class Household
class Imitation
class Immunizer
Deals with immunization strategies.
class Infector
Actual contacts and transmission in contactpool (primary template).
class Infector< LL, TIC, NoLocalInformation, true >
Time-optimized version (For NoLocalInformation && (None || Transmission logging)).
class InfectorMap
Simulator can time step and reveal some of the key data.
class LocalDiscussion
Class for local information policy 'LocalDiscussion'.
class LocationData
class LocationDataConfig
class MultiPopulation
data structure to keep multiple populations and their names consisting of 1 main grid with multiple locations a number of grids that have a concentrated population in 1 location
class NoBehaviour
NoBehaviour means that whatever beliefs a person holds, or whatever information they gather, will not result in a change in their behaviour.
class NoBelief
No beliefs w.r.t vaccination.
class NoGlobalInformation
No global information about the disease, number of infected,...
class NoLocalInformation
No information about beliefs or health status is exchanged upon contact.
class Person
Store and handle person data.
class Point2D
class PopBuilder
Initializes Population objects.
class Population
Container for persons in population.
class PopulationGenerator
class Sim
Simulator can time step and reveal some of the key data.
class SimBuilder
Builds a simulator based a configuration property tree.
class SimRunner
The simulation runner drive simulator throufgh time steps.
class SurveySeeder
Seeds the population with survey participants.
class Threshold
class TransmissionProfile
Transmission rates from disease data.
struct TravelBean
class to store travel information from 1 person
class TravelTable
class to store travel info in the form of beans these beans can be sequentially updated once per simulation day
class Vaccination
Vaccination beliefs and information have an influence on the vaccination behaviour of an individual.
Typedefs
using AgeContactProfiles = ContactPoolType::IdSubscriptArray< AgeContactProfile >
typedef void() InfectorExec(ContactPool &pool, const AgeContactProfile &profile, const TransmissionProfile &trans_profile, ContactHandler &c_handler, unsigned short int sim_day, std::shared_ptr< spdlog::logger > c_logger)
For use in the InfectorMap and Sim.
typedef boost::geometry::model::point< double, 2, boost::geometry::cs::spherical_equatorial< boost::geometry::degree > > spherical_point
using LocIndex = unsigned
template<typename T >
using locationData = std::vector< T >
Represents a data field of a location.
using ContactPoolSys = ContactPoolType::IdSubscriptArray< std::vector< ContactPool > >
ContactPoolSys contains for each of the type of pools (household, school, ...) a vector of with all of the contcatpools of the type.
Enumerations
enum VariableState { VariableState::Low = 0U, VariableState::High = 1U }
enum OutBreak {
ALL, FLANDERS, GERMANY, FRANCE,
THENETHERLANDS, WALLONIA
}
types of outbreaks,
enum HealthStatus : unsigned short int {
HealthStatus::Susceptible = 0U, HealthStatus::Exposed = 1U, HealthStatus::Infectious = 2U, HealthStatus::Symptomatic = 3U,
HealthStatus::InfectiousAndSymptomatic = 4U, HealthStatus::Recovered = 5U, HealthStatus::Immune = 6U
}
Enumerate the various health states with respect to the infection.
enum Occupation { Occupation::Nonactive, Occupation::SchoolStudent, Occupation::CollegeStudent, Occupation::Working }
enum TravelType { BUSINESS, VACATION, NOTRAVEL }
type of travel
Functions
double GeoDistance (const spherical_point &first, const spherical_point &second)
Returns the distance between two locations on earth in km.
template<typename Container , typename Index >
void FillLocationAttributeHelper (const unsigned row_index, Container &result, const stride::util::CSV &csv, const Index &label_index)
template<typename Container , typename Index , typename... Indices>
void FillLocationAttributeHelper (const unsigned row_index, Container &result, const stride::util::CSV &csv, const Index &label_index, const Indices &... label_indices)
template<typename Container , typename... Str>
Container FillLocationAttribute (const stride::util::CSV &csv, const Str &... csv_label)
constexpr unsigned int MaximumAge ()
Maximum age for Persons.
constexpr unsigned int MinAdultAge ()
Maximum age for Person's.
unsigned int EffectiveAge (unsigned int age)
Effective age (topping of at maximum).
Detailed Description
Main namespace for the project.
Typedef Documentation
AgeContactProfiles
using stride::AgeContactProfiles = typedef ContactPoolType::IdSubscriptArray<AgeContactProfile>
Definition at line 28 of file AgeContactProfiles.h.
InfectorExec
typedef void() stride::InfectorExec(ContactPool &pool, const AgeContactProfile &profile, const TransmissionProfile &trans_profile, ContactHandler &c_handler, unsigned short int sim_day, std::shared_ptr< spdlog::logger > c_logger)
For use in the InfectorMap and Sim.
Definition at line 32 of file InfectorExec.h.
spherical_point
typedef boost::geometry::model::point<double, 2, boost::geometry::cs::spherical_equatorial<boost::geometry::degree> > stride::spherical_point
Definition at line 24 of file GeoGrid.h.
LocIndex
typedef unsigned stride::LocIndex
Definition at line 29 of file GeoGrid.h.
locationData
template<typename T > using stride::locationData = typedef std::vector<T>
Represents a data field of a location.
As a result, locationData.size() should always be the same as the number of available locations.
Definition at line 32 of file GeoGrid.h.
ContactPoolSys
using stride::ContactPoolSys = typedef ContactPoolType::IdSubscriptArray<std::vector<ContactPool> >
ContactPoolSys contains for each of the type of pools (household, school, ...) a vector of with all of the contcatpools of the type.
The ContactPoolSys container is an std::array extended to be subscriptable with the enum class of the pool types.
Definition at line 32 of file ContactPoolSys.h.
Enumeration Type Documentation
VariableState
enum stride::VariableState strong
Enumerator
Low
High
Definition at line 36 of file HBM.h.
OutBreak
enum stride::OutBreak
types of outbreaks,
Enumerator
ALL
FLANDERS
break out everywhere
GERMANY
break out in Flanders
FRANCE
break out in Germany
THENETHERLANDS
break out in France
WALLONIA
break out in The Netherlands
break out in Wallonia
Definition at line 37 of file DiseaseSeeder.h.
HealthStatus
enum stride::HealthStatus : unsigned short int strong
Enumerate the various health states with respect to the infection.
Enumerator
Susceptible
Exposed
Infectious
Symptomatic
InfectiousAndSymptomatic
Recovered
Immune
Definition at line 25 of file Health.h.
Occupation
enum stride::Occupation strong
Enumerator
Nonactive
SchoolStudent
CollegeStudent
Working
Definition at line 59 of file GeoGrid.h.
TravelType
enum stride::TravelType
type of travel
Enumerator
BUSINESS
VACATION
NOTRAVEL
Definition at line 25 of file TravelTable.h.
Function Documentation
GeoDistance()
double stride::GeoDistance (const spherical_point & first, const spherical_point & second)
Returns the distance between two locations on earth in km.
Definition at line 9 of file Point2D.cpp.
References earth_radius.
Referenced by stride::GeoGrid::CalculateNearestCities().
FillLocationAttributeHelper() [1/2]
template<typename Container , typename Index > void stride::FillLocationAttributeHelper (const unsigned row_index, Container & result, const stride::util::CSV & csv, const Index & label_index) inline
Definition at line 92 of file GeoGridBuilder.h.
References boost::lexical_cast().
Referenced by FillLocationAttribute().
FillLocationAttributeHelper() [2/2]
template<typename Container , typename Index , typename... Indices> void stride::FillLocationAttributeHelper (const unsigned row_index, Container & result, const stride::util::CSV & csv, const Index & label_index, const Indices &... label_indices) inline
Definition at line 100 of file GeoGridBuilder.h.
References boost::lexical_cast().
FillLocationAttribute()
template<typename Container , typename... Str> Container stride::FillLocationAttribute (const stride::util::CSV & csv, const Str &... csv_label)
Definition at line 111 of file GeoGridBuilder.h.
References FillLocationAttributeHelper(), and stride::util::CSV::GetIndexForLabel().
MaximumAge()
constexpr unsigned int stride::MaximumAge () inline
Maximum age for Persons.
Definition at line 25 of file Age.h.
Referenced by EffectiveAge().
MinAdultAge()
constexpr unsigned int stride::MinAdultAge () inline
Maximum age for Person's.
Definition at line 28 of file Age.h.
Referenced by stride::Person::Update().
EffectiveAge()
unsigned int stride::EffectiveAge (unsigned int age) inline
Effective age (topping of at maximum).
Definition at line 31 of file Age.h.
References MaximumAge().