Stride Reference Manual: stride::DiseaseSeeder Class Reference
stride::DiseaseSeeder Class Reference
Seeds population w.r.t immunity (natural immunity, vaccination, ...) and infection.
#include <DiseaseSeeder.h>
Public Member Functions
DiseaseSeeder (const boost::property_tree::ptree &configPt, util::RNManager &rnManager)
Initializing DiseaseSeeder.
void Seed (std::shared_ptr< Population > pop)
Build the simulator.
void Seed (std::shared_ptr< stride::MultiPopulation > pop)
Build the simulator with the multipopulation.
Private Member Functions
void Vaccinate (const std::string &immunityType, const std::string &immunizationProfile, std::vector< ContactPool > &immunityPools)
Seed for vaccination/natural immunity.
Private Attributes
const boost::property_tree::ptree & m_config_pt
Run config.
util::RNManager & m_rn_manager
Random number manager.
Detailed Description
Seeds population w.r.t immunity (natural immunity, vaccination, ...) and infection.
Definition at line 50 of file DiseaseSeeder.h.
Constructor & Destructor Documentation
DiseaseSeeder()
stride::DiseaseSeeder::DiseaseSeeder (const boost::property_tree::ptree & configPt, util::RNManager & rnManager)
Initializing DiseaseSeeder.
Definition at line 42 of file DiseaseSeeder.cpp.
Member Function Documentation
Seed() [1/2]
void stride::DiseaseSeeder::Seed (std::shared_ptr< Population > pop)
Build the simulator.
Definition at line 47 of file DiseaseSeeder.cpp.
References stride::Person::GetAge(), stride::util::RNManager::GetGenerator(), stride::Person::GetHealth(), stride::Person::GetId(), stride::Health::IsSusceptible(), m_config_pt, m_rn_manager, stride::Health::StartInfection(), and Vaccinate().
Referenced by stride::SimBuilder::Build().
Seed() [2/2]
void stride::DiseaseSeeder::Seed (std::shared_ptr< stride::MultiPopulation > pop)
Build the simulator with the multipopulation.
Definition at line 80 of file DiseaseSeeder.cpp.
References stride::Person::GetAge(), stride::util::RNManager::GetGenerator(), stride::Person::GetHealth(), stride::Person::GetId(), stride::Health::IsSusceptible(), m_config_pt, m_rn_manager, stride::Health::StartInfection(), and Vaccinate().
Vaccinate()
void stride::DiseaseSeeder::Vaccinate (const std::string & immunityType, const std::string & immunizationProfile, std::vector< ContactPool > & immunityPools) private
Seed for vaccination/natural immunity.
Definition at line 129 of file DiseaseSeeder.cpp.
References stride::Immunizer::Cocoon(), m_config_pt, m_rn_manager, stride::Immunizer::Random(), and stride::util::ToLower().
Referenced by Seed().
Member Data Documentation
m_config_pt
const boost::property_tree::ptree& stride::DiseaseSeeder::m_config_pt private
Run config.
Definition at line 68 of file DiseaseSeeder.h.
Referenced by Seed(), and Vaccinate().
m_rn_manager
util::RNManager& stride::DiseaseSeeder::m_rn_manager private
Random number manager.
Definition at line 69 of file DiseaseSeeder.h.
Referenced by Seed(), and Vaccinate().
The documentation for this class was generated from the following files:
DiseaseSeeder.h
DiseaseSeeder.cpp