Stride Reference Manual: stride::util::ConfigInfo Class Reference
stride::util::ConfigInfo Class Reference
Config information.
#include <ConfigInfo.h>
Static Public Member Functions
static constexpr bool HaveOpenMP ()
static constexpr bool HaveQt5 ()
static std::string GitRevision ()
static std::string GetHostname ()
static unsigned int NumberAvailableThreads ()
static constexpr unsigned int ProcessorCount ()
Detailed Description
Config information.
Definition at line 30 of file ConfigInfo.h.
Member Function Documentation
HaveOpenMP()
static constexpr bool stride::util::ConfigInfo::HaveOpenMP () inline static
Definition at line 34 of file ConfigInfo.h.
Referenced by stride::CliController::LogSetup().
HaveQt5()
static constexpr bool stride::util::ConfigInfo::HaveQt5 () inline static
Definition at line 44 of file ConfigInfo.h.
GitRevision()
std::string stride::util::ConfigInfo::GitRevision () static
Definition at line 33 of file ConfigInfo.cpp.
References TOSTRING.
Referenced by stride::CliController::LogSetup().
GetHostname()
std::string stride::util::ConfigInfo::GetHostname () static
Definition at line 35 of file ConfigInfo.cpp.
NumberAvailableThreads()
unsigned int stride::util::ConfigInfo::NumberAvailableThreads () static
Definition at line 42 of file ConfigInfo.cpp.
Referenced by stride::CliController::LogSetup().
ProcessorCount()
static constexpr unsigned int stride::util::ConfigInfo::ProcessorCount () inline static
Definition at line 56 of file ConfigInfo.h.
The documentation for this class was generated from the following files:
ConfigInfo.h
ConfigInfo.cpp