Stride Reference Manual: stride::Immunizer Class Reference
stride::Immunizer Class Reference
Deals with immunization strategies.
#include <Immunizer.h>
Public Member Functions
Immunizer (util::RNManager &rnManager)
void Random (const std::vector< ContactPool > &pools, std::vector< double > &immunityDistribution, double immunityLinkProbability)
Random immunization.
void Cocoon (const std::vector< ContactPool > &pools, std::vector< double > &immunityDistribution, double immunityLinkProbability)
Cocoon immunization.
Private Attributes
util::RNManager & m_rn_manager
Random number manager.
Detailed Description
Deals with immunization strategies.
Definition at line 35 of file Immunizer.h.
Constructor & Destructor Documentation
Immunizer()
stride::Immunizer::Immunizer (util::RNManager & rnManager) explicit
Definition at line 33 of file Immunizer.cpp.
Member Function Documentation
Random()
void stride::Immunizer::Random (const std::vector< ContactPool > & pools, std::vector< double > & immunityDistribution, double immunityLinkProbability)
Random immunization.
Definition at line 35 of file Immunizer.cpp.
References stride::Person::GetAge(), stride::util::RNManager::GetGenerator(), stride::Person::GetHealth(), stride::ContactPool::GetMember(), stride::ContactPool::GetSize(), stride::Health::IsImmune(), m_rn_manager, stride::util::RNManager::RandomShuffle(), and stride::Health::SetSusceptible().
Referenced by stride::DiseaseSeeder::Vaccinate().
Cocoon()
void stride::Immunizer::Cocoon (const std::vector< ContactPool > & pools, std::vector< double > & immunityDistribution, double immunityLinkProbability)
Cocoon immunization.
Definition at line 94 of file Immunizer.cpp.
Referenced by stride::DiseaseSeeder::Vaccinate().
Member Data Documentation
m_rn_manager
util::RNManager& stride::Immunizer::m_rn_manager private
Random number manager.
Definition at line 50 of file Immunizer.h.
Referenced by Random().
The documentation for this class was generated from the following files:
Immunizer.h
Immunizer.cpp