Stride Reference Manual: stride::qt::Window Class Reference
stride::qt::Window Class Reference
The main window in the stride program; is responsible for the layout of the window.
#include <Window.h>
Public Slots
void DrawMap ()
Draw the current map in the window.
void EditConf ()
Edit the simulation configuration (and run a new simulation).
void SaveMap (bool askForPath=true)
Save the current map to a file.
Public Member Functions
Window (QSim *_sim=nullptr)
(Default) Constructor.
~Window ()=default
Destructor.
bool LoadImage (const QString &fileName)
Loads the map image.
void AddMap (std::shared_ptr< Map > newMap)
Adds a new Map into the window.
stride::Point2D ConvertLatLongToPixel (double latitude, double longitude) const
Convert a latitude and longitude coordinate to a pixel in the Window.
stride::Point2D ConvertLatLongToPixel (const spherical_point &p) const
Convert a point (in the latitude and longitude coordinate system) to a pixel in the Window.
void SetCurrentDay (int day)
Set the current day of the simulation in the gui.
void SetStats (std::shared_ptr< Stats > _stats)
Set the Stats object: needed to show statistics.
void SetForm (QConfig *form)
Set the config form of the window (the editable part on the right).
QLineEdit * AddSimButtons (std::vector< QPushButton *> simButtons, QPushButton *xDaysButton)
Add the simulation buttons to the window.
void SetConfig (boost::property_tree::ptree *config)
Add the simulation config.
Private Slots
void ZoomIn ()
Zoom in on the map with factor 1.25.
void ZoomOut ()
Zoom out on the map with factor 0.8.
void NormalSize ()
Adjusts the size of the Map.
void FitToWindow ()
Fill the entire window with the Map (doesn't respect aspect ratio).
void ToggleFilterSchool ()
Filter the locations by schools.
void ToggleFilterWorkplaces ()
Filter the locations by workplaces.
void TogglefilterAcademies ()
Filter the locations by academies.
void ToggleFilterCommunities ()
Filter the locations by communities.
void ToggleCommutings ()
(Un)hide the commutings lines.
void ShowControls () const
Show the controls of the gui.
void ShowColorCoding () const
Show the color coding is used in the gui.
Private Member Functions
bool event (QEvent *event) override
void mousePressEvent (QMouseEvent *event) override
void mouseMoveEvent (QMouseEvent *event) override
void mouseReleaseEvent (QMouseEvent *event) override
void CreateActions ()
void UpdateActions ()
void ScaleImage (double factor)
void AdjustScrollBar (QScrollBar *scrollBar, double factor)
void SetBordersOfScrollBars ()
void SetValues ()
QPointF TranslateToOriginal (const QPointF &pos) const
Private Attributes
QImage originalImage
The Map images.
QImage image
The Map canvas.
QLabel * imageLabel
The entire display (image + points).
QScrollArea * scrollAreaImage
Scroll area for image.
QVBoxLayout * vlayout
QVBoxLayout * vlayout2
QHBoxLayout * hlayout
QProgressBar * progressBar
QWidget * mainWidget
QWidget * topWidget
QConfig * qconfig
QWidget * bottomWidget
QHBoxLayout * hlayout2
QLabel * currentDayText
QLineEdit * numDaysEdit
double scaleFactor
Scale factor for the image.
double hScrollMax
Maximum value of the horizontal scroll bar.
double vScrollMax
Maximum value of the vertical scroll bar.
double hValue
Current horizontal value of the scroll bar.
double vValue
Current vertical value of the scroll bar.
Selection< QLocation > selection
std::unique_ptr< QRubberBand > rubberBand
QPoint originRubberBand
QAction * zoomInAct
QAction * zoomOutAct
QAction * normalSizeAct
QAction * fitToWindowAct
std::shared_ptr< Map > map
std::shared_ptr< Stats > stats
QSim * sim
Need pointer to QSim so we can send signals.
boost::property_tree::ptree * config_run
Simulation configuration.
int currentDay
Current day in the simulation.
Detailed Description
The main window in the stride program; is responsible for the layout of the window.
Definition at line 37 of file Window.h.
Constructor & Destructor Documentation
Window()
stride::qt::Window::Window (QSim * _sim = nullptr)
(Default) Constructor.
Parameters
_sim Pointer to QSim: needed so we can send signals.
Screen layout: mainWidget (vlayout)
topWidget (hlayout)
scrollArea (imageLabel)
bottomWidget
vlayout2
hlayout2
currentDayText
sim buttons
progress bar
Definition at line 7 of file Window.cpp.
References bottomWidget, CreateActions(), currentDayText, fitToWindowAct, hlayout, hlayout2, imageLabel, mainWidget, progressBar, scrollAreaImage, topWidget, vlayout, and vlayout2.
~Window()
stride::qt::Window::~Window () default
Destructor.
Member Function Documentation
LoadImage()
bool stride::qt::Window::LoadImage (const QString & fileName)
Loads the map image.
Parameters
fileName Path to the Map image.
Definition at line 104 of file Window.cpp.
References image, originalImage, scaleFactor, and UpdateActions().
AddMap()
void stride::qt::Window::AddMap (std::shared_ptr< Map > newMap)
Adds a new Map into the window.
Parameters
newMap The new Map.
Definition at line 123 of file Window.cpp.
References DrawMap(), fitToWindowAct, imageLabel, and map.
ConvertLatLongToPixel() [1/2]
stride::Point2D stride::qt::Window::ConvertLatLongToPixel (double latitude, double longitude) const
Convert a latitude and longitude coordinate to a pixel in the Window.
Parameters
latitude The latitude value of the coordinate.
longitude The longitude value of the coordinate.
Returns
The converted coordinate.
Definition at line 468 of file Window.cpp.
References image, stride::qt::LEFTUPPER_LATITUDE, stride::qt::LEFTUPPER_LONGITUDE, stride::qt::RIGHTUNDER_LATITUDE, and stride::qt::RIGHTUNDER_LONGITUDE.
Referenced by stride::qt::MapBuilder::BuildMap(), and ConvertLatLongToPixel().
ConvertLatLongToPixel() [2/2]
stride::Point2D stride::qt::Window::ConvertLatLongToPixel (const spherical_point & p) const
Convert a point (in the latitude and longitude coordinate system) to a pixel in the Window.
Parameters
p The point (in the latitude and longitude coordinate system) .
Returns
The converted coordinate.
Definition at line 486 of file Window.cpp.
References ConvertLatLongToPixel().
SetCurrentDay()
void stride::qt::Window::SetCurrentDay (int day)
Set the current day of the simulation in the gui.
Parameters
day The current day (0 = first day of simulation, -1 = last day).
Definition at line 491 of file Window.cpp.
References config_run, currentDay, currentDayText, and progressBar.
SetStats()
void stride::qt::Window::SetStats (std::shared_ptr< Stats > _stats)
Set the Stats object: needed to show statistics.
Parameters
_stats Stats object.
Definition at line 503 of file Window.cpp.
References stride::qt::Stats::AgeStats(), stride::qt::Stats::CitiesStats(), stride::qt::Stats::HouseholdStats(), stats, and stride::qt::Stats::WorkplaceStats().
SetForm()
void stride::qt::Window::SetForm (QConfig * form)
Set the config form of the window (the editable part on the right).
Parameters
form The form.
Definition at line 102 of file Window.cpp.
References qconfig.
AddSimButtons()
QLineEdit * stride::qt::Window::AddSimButtons (std::vector< QPushButton *> simButtons, QPushButton * xDaysButton)
Add the simulation buttons to the window.
("Next Day"/"Last Day" button)
Parameters
simButtons List of the sim buttons.
runXDaysButton The "Run X Days" button (passed separately, because we need to add a line edit).
Returns
Pointer to line edit, so we can easily retrieve the value.
Definition at line 72 of file Window.cpp.
References config_run, currentDayText, hlayout2, and numDaysEdit.
SetConfig()
void stride::qt::Window::SetConfig (boost::property_tree::ptree * config)
Add the simulation config.
Parameters
config The configuration.
Definition at line 100 of file Window.cpp.
References config_run.
DrawMap
void stride::qt::Window::DrawMap () slot
Draw the current map in the window.
Definition at line 132 of file Window.cpp.
References image, imageLabel, map, originalImage, SetBordersOfScrollBars(), and SetValues().
Referenced by AddMap(), mouseMoveEvent(), mousePressEvent(), ToggleCommutings(), TogglefilterAcademies(), ToggleFilterCommunities(), ToggleFilterSchool(), and ToggleFilterWorkplaces().
EditConf
void stride::qt::Window::EditConf () slot
Edit the simulation configuration (and run a new simulation).
Definition at line 174 of file Window.cpp.
References stride::qt::QConfig::EditConfig(), and qconfig.
Referenced by CreateActions().
SaveMap
void stride::qt::Window::SaveMap (bool askForPath = true) slot
Save the current map to a file.
Parameters
askForPath Ask the user where to save the map if true.
Definition at line 144 of file Window.cpp.
References config_run, currentDay, stride::util::FileSys::GetCurrentDir(), and image.
Referenced by CreateActions().
ZoomIn
void stride::qt::Window::ZoomIn () private slot
Zoom in on the map with factor 1.25.
Definition at line 176 of file Window.cpp.
References ScaleImage().
Referenced by CreateActions().
ZoomOut
void stride::qt::Window::ZoomOut () private slot
Zoom out on the map with factor 0.8.
Definition at line 178 of file Window.cpp.
References ScaleImage().
Referenced by CreateActions().
NormalSize
void stride::qt::Window::NormalSize () private slot
Adjusts the size of the Map.
Definition at line 180 of file Window.cpp.
References imageLabel, and scaleFactor.
Referenced by CreateActions(), and FitToWindow().
FitToWindow
void stride::qt::Window::FitToWindow () private slot
Fill the entire window with the Map (doesn't respect aspect ratio).
Definition at line 186 of file Window.cpp.
References fitToWindowAct, NormalSize(), scrollAreaImage, and UpdateActions().
Referenced by CreateActions().
ToggleFilterSchool
void stride::qt::Window::ToggleFilterSchool () private slot
Filter the locations by schools.
Definition at line 196 of file Window.cpp.
References DrawMap(), and map.
Referenced by CreateActions().
ToggleFilterWorkplaces
void stride::qt::Window::ToggleFilterWorkplaces () private slot
Filter the locations by workplaces.
Definition at line 202 of file Window.cpp.
References DrawMap(), and map.
Referenced by CreateActions().
TogglefilterAcademies
void stride::qt::Window::TogglefilterAcademies () private slot
Filter the locations by academies.
Definition at line 208 of file Window.cpp.
References DrawMap(), and map.
Referenced by CreateActions().
ToggleFilterCommunities
void stride::qt::Window::ToggleFilterCommunities () private slot
Filter the locations by communities.
Definition at line 214 of file Window.cpp.
References DrawMap(), and map.
Referenced by CreateActions().
ToggleCommutings
void stride::qt::Window::ToggleCommutings () private slot
(Un)hide the commutings lines.
Definition at line 220 of file Window.cpp.
References DrawMap(), and map.
Referenced by CreateActions().
ShowControls
void stride::qt::Window::ShowControls () const private slot
Show the controls of the gui.
Definition at line 226 of file Window.cpp.
Referenced by CreateActions().
ShowColorCoding
void stride::qt::Window::ShowColorCoding () const private slot
Show the color coding is used in the gui.
Definition at line 238 of file Window.cpp.
Referenced by CreateActions().
event()
bool stride::qt::Window::event (QEvent * event) override private
Definition at line 259 of file Window.cpp.
References stride::qt::QDrawable::IsVisible(), map, scaleFactor, selection, SetBordersOfScrollBars(), SetValues(), and TranslateToOriginal().
Referenced by mouseMoveEvent(), mousePressEvent(), and mouseReleaseEvent().
mousePressEvent()
void stride::qt::Window::mousePressEvent (QMouseEvent * event) override private
Definition at line 293 of file Window.cpp.
References DrawMap(), event(), map, originRubberBand, rubberBand, scaleFactor, selection, and TranslateToOriginal().
mouseMoveEvent()
void stride::qt::Window::mouseMoveEvent (QMouseEvent * event) override private
Definition at line 322 of file Window.cpp.
References DrawMap(), event(), map, originRubberBand, rubberBand, selection, and TranslateToOriginal().
mouseReleaseEvent()
void stride::qt::Window::mouseReleaseEvent (QMouseEvent * event) override private
Definition at line 344 of file Window.cpp.
References event(), map, rubberBand, and selection.
CreateActions()
void stride::qt::Window::CreateActions () private
Definition at line 354 of file Window.cpp.
References EditConf(), FitToWindow(), fitToWindowAct, NormalSize(), normalSizeAct, SaveMap(), ShowColorCoding(), ShowControls(), ToggleCommutings(), TogglefilterAcademies(), ToggleFilterCommunities(), ToggleFilterSchool(), ToggleFilterWorkplaces(), ZoomIn(), zoomInAct, ZoomOut(), and zoomOutAct.
Referenced by Window().
UpdateActions()
void stride::qt::Window::UpdateActions () private
Definition at line 403 of file Window.cpp.
References fitToWindowAct, normalSizeAct, zoomInAct, and zoomOutAct.
Referenced by FitToWindow(), and LoadImage().
ScaleImage()
void stride::qt::Window::ScaleImage (double factor) private
Definition at line 410 of file Window.cpp.
References AdjustScrollBar(), imageLabel, scaleFactor, scrollAreaImage, zoomInAct, and zoomOutAct.
Referenced by ZoomIn(), and ZoomOut().
AdjustScrollBar()
void stride::qt::Window::AdjustScrollBar (QScrollBar * scrollBar, double factor) private
Definition at line 425 of file Window.cpp.
Referenced by ScaleImage().
SetBordersOfScrollBars()
void stride::qt::Window::SetBordersOfScrollBars () private
Definition at line 430 of file Window.cpp.
References hScrollMax, scrollAreaImage, and vScrollMax.
Referenced by DrawMap(), and event().
SetValues()
void stride::qt::Window::SetValues () private
Definition at line 438 of file Window.cpp.
References hValue, scrollAreaImage, and vValue.
Referenced by DrawMap(), and event().
TranslateToOriginal()
QPointF stride::qt::Window::TranslateToOriginal (const QPointF & pos) const private
Definition at line 444 of file Window.cpp.
References hScrollMax, hValue, image, scaleFactor, scrollAreaImage, vScrollMax, and vValue.
Referenced by event(), mouseMoveEvent(), and mousePressEvent().
Member Data Documentation
originalImage
QImage stride::qt::Window::originalImage private
The Map images.
Definition at line 148 of file Window.h.
Referenced by DrawMap(), and LoadImage().
image
QImage stride::qt::Window::image private
The Map canvas.
Definition at line 149 of file Window.h.
Referenced by ConvertLatLongToPixel(), DrawMap(), LoadImage(), SaveMap(), and TranslateToOriginal().
imageLabel
QLabel* stride::qt::Window::imageLabel private
The entire display (image + points).
Definition at line 150 of file Window.h.
Referenced by AddMap(), DrawMap(), NormalSize(), ScaleImage(), and Window().
scrollAreaImage
QScrollArea* stride::qt::Window::scrollAreaImage private
Scroll area for image.
Definition at line 151 of file Window.h.
Referenced by FitToWindow(), ScaleImage(), SetBordersOfScrollBars(), SetValues(), TranslateToOriginal(), and Window().
vlayout
QVBoxLayout* stride::qt::Window::vlayout private
Definition at line 152 of file Window.h.
Referenced by Window().
vlayout2
QVBoxLayout* stride::qt::Window::vlayout2 private
Definition at line 153 of file Window.h.
Referenced by Window().
hlayout
QHBoxLayout* stride::qt::Window::hlayout private
Definition at line 154 of file Window.h.
Referenced by Window().
progressBar
QProgressBar* stride::qt::Window::progressBar private
Definition at line 155 of file Window.h.
Referenced by SetCurrentDay(), and Window().
mainWidget
QWidget* stride::qt::Window::mainWidget private
Definition at line 156 of file Window.h.
Referenced by Window().
topWidget
QWidget* stride::qt::Window::topWidget private
Definition at line 157 of file Window.h.
Referenced by Window().
qconfig
QConfig* stride::qt::Window::qconfig private
Definition at line 158 of file Window.h.
Referenced by EditConf(), and SetForm().
bottomWidget
QWidget* stride::qt::Window::bottomWidget private
Definition at line 159 of file Window.h.
Referenced by Window().
hlayout2
QHBoxLayout* stride::qt::Window::hlayout2 private
Definition at line 160 of file Window.h.
Referenced by AddSimButtons(), and Window().
currentDayText
QLabel* stride::qt::Window::currentDayText private
Definition at line 161 of file Window.h.
Referenced by AddSimButtons(), SetCurrentDay(), and Window().
numDaysEdit
QLineEdit* stride::qt::Window::numDaysEdit private
Definition at line 162 of file Window.h.
Referenced by AddSimButtons().
scaleFactor
double stride::qt::Window::scaleFactor private
Scale factor for the image.
Definition at line 164 of file Window.h.
Referenced by event(), LoadImage(), mousePressEvent(), NormalSize(), ScaleImage(), and TranslateToOriginal().
hScrollMax
double stride::qt::Window::hScrollMax private
Maximum value of the horizontal scroll bar.
Definition at line 165 of file Window.h.
Referenced by SetBordersOfScrollBars(), and TranslateToOriginal().
vScrollMax
double stride::qt::Window::vScrollMax private
Maximum value of the vertical scroll bar.
Definition at line 166 of file Window.h.
Referenced by SetBordersOfScrollBars(), and TranslateToOriginal().
hValue
double stride::qt::Window::hValue private
Current horizontal value of the scroll bar.
Definition at line 167 of file Window.h.
Referenced by SetValues(), and TranslateToOriginal().
vValue
double stride::qt::Window::vValue private
Current vertical value of the scroll bar.
Definition at line 168 of file Window.h.
Referenced by SetValues(), and TranslateToOriginal().
selection
Selection<QLocation> stride::qt::Window::selection private
Definition at line 170 of file Window.h.
Referenced by event(), mouseMoveEvent(), mousePressEvent(), and mouseReleaseEvent().
rubberBand
std::unique_ptr<QRubberBand> stride::qt::Window::rubberBand private
Definition at line 171 of file Window.h.
Referenced by mouseMoveEvent(), mousePressEvent(), and mouseReleaseEvent().
originRubberBand
QPoint stride::qt::Window::originRubberBand private
Definition at line 172 of file Window.h.
Referenced by mouseMoveEvent(), and mousePressEvent().
zoomInAct
QAction* stride::qt::Window::zoomInAct private
Definition at line 174 of file Window.h.
Referenced by CreateActions(), ScaleImage(), and UpdateActions().
zoomOutAct
QAction* stride::qt::Window::zoomOutAct private
Definition at line 175 of file Window.h.
Referenced by CreateActions(), ScaleImage(), and UpdateActions().
normalSizeAct
QAction* stride::qt::Window::normalSizeAct private
Definition at line 176 of file Window.h.
Referenced by CreateActions(), and UpdateActions().
fitToWindowAct
QAction* stride::qt::Window::fitToWindowAct private
Definition at line 177 of file Window.h.
Referenced by AddMap(), CreateActions(), FitToWindow(), UpdateActions(), and Window().
map
std::shared_ptr<Map> stride::qt::Window::map private
Definition at line 179 of file Window.h.
Referenced by AddMap(), DrawMap(), event(), mouseMoveEvent(), mousePressEvent(), mouseReleaseEvent(), ToggleCommutings(), TogglefilterAcademies(), ToggleFilterCommunities(), ToggleFilterSchool(), and ToggleFilterWorkplaces().
stats
std::shared_ptr<Stats> stride::qt::Window::stats private
Definition at line 180 of file Window.h.
Referenced by SetStats().
sim
QSim* stride::qt::Window::sim private
Need pointer to QSim so we can send signals.
Definition at line 182 of file Window.h.
config_run
boost::property_tree::ptree* stride::qt::Window::config_run private
Simulation configuration.
Definition at line 183 of file Window.h.
Referenced by AddSimButtons(), SaveMap(), SetConfig(), and SetCurrentDay().
currentDay
int stride::qt::Window::currentDay private
Current day in the simulation.
Definition at line 184 of file Window.h.
Referenced by SaveMap(), and SetCurrentDay().
The documentation for this class was generated from the following files:
Window.h
Window.cpp