Stride Reference Manual: stride::GuiRunner Class Reference
stride::GuiRunner Class Reference
The simulation runner for the gui, inherits SimRunner.
#include <GuiRunner.h>
Public Slots
void Run ()
Run simulator for as many steps/days as indicated in config.
void Run (int numSteps)
Run simulator for numSteps steps/days.
void StopSim ()
Stop the simulation.
Public Member Functions
GuiRunner ()=default
Default constructor.
GuiRunner (const boost::property_tree::ptree &configPt, std::shared_ptr< stride::MultiPopulation > multipop)
Initialization with property tree.
GuiRunner (const boost::property_tree::ptree &configPt, std::shared_ptr< GeoGrid > grid)
virtual ~GuiRunner ()=default
Destructor.
void SetUp (boost::property_tree::ptree configPt, std::shared_ptr< stride::MultiPopulation > multipop)
Set up the runner.
void SetUp (boost::property_tree::ptree configPt, std::shared_ptr< GeoGrid > grid)
Set up the runner.
std::shared_ptr< stride::GeoGrid > GetGeoGrid ()
Return the GeoGrid.
Public Member Functions inherited from stride::SimRunner
SimRunner ()=default
Default constructor.
SimRunner (const boost::property_tree::ptree &configPt, std::shared_ptr< MultiPopulation > multipop)
SimRunner (const boost::property_tree::ptree &configPt, std::shared_ptr< Population > pop)
~SimRunner () override=default
Destructor.
const util::Stopwatch & GetClock () const
Return the run & sim configuration.
const boost::property_tree::ptree & GetConfig () const
Return the run & sim configuration.
std::shared_ptr< Sim > GetSim () const
Return the Simulator.
virtual void Run ()
Run simulator for as many steps/days as indicated in config.
void Run (unsigned int numSteps)
Run simulator for numSteps steps/days.
Public Member Functions inherited from stride::util::Subject< stride::sim_event::Id >
Subject ()=default
virtual ~Subject ()
void Register (const std::shared_ptr< U > &u, CallbackType f)
void Unregister (const std::shared_ptr< U > &u)
void UnregisterAll ()
void Notify (const EventType &e)
Private Attributes
std::shared_ptr< stride::GeoGrid > geoGrid
bool stopSim
User can set this to true to stop the sim.
Additional Inherited Members
Public Types inherited from stride::util::Subject< stride::sim_event::Id >
using EventType = stride::sim_event::Id
using CallbackType = std::function< void(const EventType &)>
Protected Attributes inherited from stride::SimRunner
util::Stopwatch m_clock
Stopwatch for timing the computation.
boost::property_tree::ptree m_config_pt
Ptree with configuration.
std::string m_output_prefix
Prefix for output data files.
std::shared_ptr< Sim > m_sim
Simulator object.
Detailed Description
The simulation runner for the gui, inherits SimRunner.
Has a few slots that can be called by the gui.
Definition at line 24 of file GuiRunner.h.
Constructor & Destructor Documentation
GuiRunner() [1/3]
stride::GuiRunner::GuiRunner () default
Default constructor.
Allow default constructor, so we can set up the simulation at a later time.
GuiRunner() [2/3]
stride::GuiRunner::GuiRunner (const boost::property_tree::ptree & configPt, std::shared_ptr< stride::MultiPopulation > multipop) explicit
Initialization with property tree.
Parameters
configPt config info for run and for config of simulator
Definition at line 21 of file GuiRunner.cpp.
References geoGrid, stride::SimRunner::m_clock, stride::util::Subject< stride::sim_event::Id >::Notify(), stride::util::Stopwatch< T >::Start(), and stride::util::Stopwatch< T >::Stop().
GuiRunner() [3/3]
stride::GuiRunner::GuiRunner (const boost::property_tree::ptree & configPt, std::shared_ptr< GeoGrid > grid) explicit
Definition at line 33 of file GuiRunner.cpp.
References geoGrid, stride::SimRunner::m_clock, stride::util::Subject< stride::sim_event::Id >::Notify(), stride::util::Stopwatch< T >::Start(), and stride::util::Stopwatch< T >::Stop().
~GuiRunner()
virtual stride::GuiRunner::~GuiRunner () virtual default
Destructor.
Member Function Documentation
SetUp() [1/2]
void stride::GuiRunner::SetUp (boost::property_tree::ptree configPt, std::shared_ptr< stride::MultiPopulation > multipop)
Set up the runner.
Is called automatically in the constructor, only use to 'reset' the runner with a different configuration and multipop.
Definition at line 45 of file GuiRunner.cpp.
References stride::Sim::Create(), geoGrid, stride::SimRunner::m_config_pt, stride::SimRunner::m_output_prefix, and stride::SimRunner::m_sim.
SetUp() [2/2]
void stride::GuiRunner::SetUp (boost::property_tree::ptree configPt, std::shared_ptr< GeoGrid > grid)
Set up the runner.
Is called automatically in the constructor, only use to 'reset' the runner with a different configuration and geogrid.
GetGeoGrid()
std::shared_ptr<stride::GeoGrid> stride::GuiRunner::GetGeoGrid () inline
Return the GeoGrid.
Definition at line 54 of file GuiRunner.h.
References geoGrid.
Run [1/2]
void stride::GuiRunner::Run () slot
Run simulator for as many steps/days as indicated in config.
Definition at line 104 of file GuiRunner.cpp.
References stride::SimRunner::m_config_pt.
Run [2/2]
void stride::GuiRunner::Run (int numSteps) slot
Run simulator for numSteps steps/days.
Definition at line 63 of file GuiRunner.cpp.
References stride::SimRunner::m_clock, stride::SimRunner::m_config_pt, stride::SimRunner::m_sim, stride::util::Subject< stride::sim_event::Id >::Notify(), stride::util::Stopwatch< T >::Start(), stride::util::Stopwatch< T >::Stop(), and stopSim.
StopSim
void stride::GuiRunner::StopSim () slot
Stop the simulation.
Definition at line 106 of file GuiRunner.cpp.
References stopSim.
Member Data Documentation
geoGrid
std::shared_ptr<stride::GeoGrid> stride::GuiRunner::geoGrid private
Definition at line 67 of file GuiRunner.h.
Referenced by GetGeoGrid(), GuiRunner(), and SetUp().
stopSim
bool stride::GuiRunner::stopSim private
User can set this to true to stop the sim.
Definition at line 69 of file GuiRunner.h.
Referenced by Run(), and StopSim().
The documentation for this class was generated from the following files:
GuiRunner.h
GuiRunner.cpp