Stride Reference Manual: stride::qt::QDrawable Class Reference
stride::qt::QDrawable Class Reference abstract
Represents a drawable object that can be drawn on the Map.
#include <QDrawable.h>
Public Member Functions
QDrawable ()=default
Default Constructor.
QDrawable (double x, double y, QColor color=Qt::red, double radius=20.0)
Constructor.
~QDrawable () override=default
Destructor.
virtual void Draw (QPainter &painter) const =0
Draws the object.
const QPointF & GetPoint () const
Get the pixel of this object on the Map.
const QColor & GetColor () const
Get the color of the object drawn on the Map for this site.
virtual const QString GetTooltipText () const
Get the tooltip information that needs to be displayed whenever the user hovers over this object.
double GetRadius () const
Get the radius of the point of this object.
void SetSelected (bool select)
(Un)select the object
void SetVisibility (bool vis)
Set the visibility of the object.
bool IsVisible () const
Check if the object is visible (invisible if filtered out).
Protected Attributes
QColor color
The color of the object.
QPointF point
The pixel on the Map.
double radius
The radius of the object (in pixels).
QString tooltipText
The tooltip information.
bool selected
Check if the user has selected this object.
bool visible
Check if the object is visible (invisible if filtered out).
Detailed Description
Represents a drawable object that can be drawn on the Map.
Definition at line 15 of file QDrawable.h.
Constructor & Destructor Documentation
QDrawable() [1/2]
stride::qt::QDrawable::QDrawable () default
Default Constructor.
QDrawable() [2/2]
stride::qt::QDrawable::QDrawable (double x, double y, QColor color = Qt::red, double radius = 20.0)
Constructor.
Parameters
x The x pixel relative to the Map.
x The y pixel relative to the Map.
color (optional) The color of the object drawn on the Map for this site.
radius (optional) The radius of the object drawn on the Map for this site.
Definition at line 6 of file QDrawable.cpp.
References tooltipText.
~QDrawable()
stride::qt::QDrawable::~QDrawable () override default
Destructor.
Member Function Documentation
Draw()
virtual void stride::qt::QDrawable::Draw (QPainter & painter) const pure virtual
Draws the object.
Parameters
painter The painter that will be used.
Implemented in stride::qt::QCommuting, and stride::qt::QLocation.
GetPoint()
const QPointF & stride::qt::QDrawable::GetPoint () const
Get the pixel of this object on the Map.
Returns
The QPoint of this object. (the pixel on the map)
Definition at line 13 of file QDrawable.cpp.
References point.
Referenced by stride::qt::QLocation::Draw(), and stride::qt::QCommuting::Draw().
GetColor()
const QColor & stride::qt::QDrawable::GetColor () const
Get the color of the object drawn on the Map for this site.
Returns
The color of the object drawn on the Map for this site.
Definition at line 15 of file QDrawable.cpp.
References color.
Referenced by stride::qt::QLocation::Draw(), and stride::qt::QCommuting::Draw().
GetTooltipText()
const QString stride::qt::QDrawable::GetTooltipText () const virtual
Get the tooltip information that needs to be displayed whenever the user hovers over this object.
Returns
The tooltip information.
Reimplemented in stride::qt::QLocation.
Definition at line 17 of file QDrawable.cpp.
References tooltipText.
GetRadius()
double stride::qt::QDrawable::GetRadius () const
Get the radius of the point of this object.
Returns
The radius (in pixels).
Definition at line 19 of file QDrawable.cpp.
References radius.
Referenced by stride::qt::QLocation::Draw(), stride::qt::QCommuting::Draw(), and stride::qt::Map::GetObject().
SetSelected()
void stride::qt::QDrawable::SetSelected (bool select)
(Un)select the object
Parameters
select True if selected.
Definition at line 21 of file QDrawable.cpp.
References selected.
SetVisibility()
void stride::qt::QDrawable::SetVisibility (bool vis)
Set the visibility of the object.
Parameters
vis True if visible.
Definition at line 23 of file QDrawable.cpp.
References visible.
IsVisible()
bool stride::qt::QDrawable::IsVisible () const
Check if the object is visible (invisible if filtered out).
Returns
True if visible.
Definition at line 25 of file QDrawable.cpp.
References visible.
Referenced by stride::qt::Window::event().
Member Data Documentation
color
QColor stride::qt::QDrawable::color protected
The color of the object.
Definition at line 64 of file QDrawable.h.
Referenced by stride::qt::QLocation::Draw(), and GetColor().
point
QPointF stride::qt::QDrawable::point protected
The pixel on the Map.
Definition at line 65 of file QDrawable.h.
Referenced by GetPoint().
radius
double stride::qt::QDrawable::radius protected
The radius of the object (in pixels).
Definition at line 66 of file QDrawable.h.
Referenced by GetRadius(), stride::qt::QCommuting::QCommuting(), and stride::qt::QLocation::QLocation().
tooltipText
QString stride::qt::QDrawable::tooltipText protected
The tooltip information.
Definition at line 67 of file QDrawable.h.
Referenced by GetTooltipText(), stride::qt::QCommuting::QCommuting(), and QDrawable().
selected
bool stride::qt::QDrawable::selected protected
Check if the user has selected this object.
Definition at line 68 of file QDrawable.h.
Referenced by stride::qt::QLocation::Draw(), and SetSelected().
visible
bool stride::qt::QDrawable::visible protected
Check if the object is visible (invisible if filtered out).
Definition at line 69 of file QDrawable.h.
Referenced by stride::qt::QLocation::Draw(), stride::qt::QCommuting::Draw(), IsVisible(), and SetVisibility().
The documentation for this class was generated from the following files:
QDrawable.h
QDrawable.cpp