Stride Reference Manual: main.cpp File Reference
sim/main.cpp File Reference
Main program: command line handling.
#include "sim/CliController.h"
#include "sim/GuiController.h"
#include "util/FileSys.h"
#include "util/RunConfigManager.h"
#include "util/StringUtils.h"
#include "util/TimeStamp.h"
#include <tclap/CmdLine.h>
#include <iostream>
#include <regex>
#include <string>
#include <vector>
Functions
int main (int argc, char **argv)
Main program of the stride simulator.
Detailed Description
Main program: command line handling.
Definition in file sim/main.cpp.
Function Documentation
main()
int main (int argc, char ** argv)
Main program of the stride simulator.
Definition at line 41 of file sim/main.cpp.
References stride::GuiController::Control(), stride::CliController::Control(), stride::CliController::GeneratePopulation(), and stride::util::Tokenize().