Stride Reference Manual: stride::SimBuilder Class Reference
stride::SimBuilder Class Reference
Builds a simulator based a configuration property tree.
#include <SimBuilder.h>
Public Member Functions
SimBuilder (const boost::property_tree::ptree &configPt)
Initializing SimBuilder.
std::shared_ptr< Sim > Build (std::shared_ptr< Sim > sim, std::shared_ptr< Population > pop)
Build the simulator and return it afterwards.
std::shared_ptr< Sim > Build (std::shared_ptr< Population > pop)
Build the simulator with given pop.
std::shared_ptr< Sim > Build (std::shared_ptr< Sim > sim, std::shared_ptr< stride::MultiPopulation > pop, bool travel=true)
Build with given multipo.
Private Member Functions
boost::property_tree::ptree ReadAgeContactPtree ()
Get the contact configuration data.
boost::property_tree::ptree ReadDiseasePtree ()
Get the disease configuration data.
Private Attributes
boost::property_tree::ptree m_config_pt
Run config in ptree.
Detailed Description
Builds a simulator based a configuration property tree.
It
reads any additional configuration files (disease, contact, ...)
initializes calendar and random number manager for the simulator
builds a population and contact pool system (
See also
PopulationBuilder)
deals with health and immunity (
See also
HealthSeeder,
DiseaseBuilder)
Definition at line 39 of file SimBuilder.h.
Constructor & Destructor Documentation
SimBuilder()
stride::SimBuilder::SimBuilder (const boost::property_tree::ptree & configPt) explicit
Initializing SimBuilder.
Definition at line 42 of file SimBuilder.cpp.
Member Function Documentation
Build() [1/3]
std::shared_ptr<Sim> stride::SimBuilder::Build (std::shared_ptr< Sim > sim, std::shared_ptr< Population > pop)
Build the simulator and return it afterwards.
Build() [2/3]
std::shared_ptr< Sim > stride::SimBuilder::Build (std::shared_ptr< Population > pop)
Build the simulator with given pop.
Definition at line 172 of file SimBuilder.cpp.
References stride::ContactPoolType::IdList, m_config_pt, ReadAgeContactPtree(), ReadDiseasePtree(), stride::HealthSeeder::Seed(), stride::DiseaseSeeder::Seed(), and stride::ContactLogMode::ToMode().
Build() [3/3]
std::shared_ptr<Sim> stride::SimBuilder::Build (std::shared_ptr< Sim > sim, std::shared_ptr< stride::MultiPopulation > pop, bool travel = true)
Build with given multipo.
ReadAgeContactPtree()
ptree stride::SimBuilder::ReadAgeContactPtree () private
Get the contact configuration data.
Definition at line 246 of file SimBuilder.cpp.
References stride::util::FileSys::GetDataDir(), m_config_pt, and stride::util::FileSys::ReadPtreeFile().
Referenced by Build().
ReadDiseasePtree()
ptree stride::SimBuilder::ReadDiseasePtree () private
Get the disease configuration data.
Definition at line 253 of file SimBuilder.cpp.
References stride::util::FileSys::GetDataDir(), m_config_pt, and stride::util::FileSys::ReadPtreeFile().
Referenced by Build().
Member Data Documentation
m_config_pt
boost::property_tree::ptree stride::SimBuilder::m_config_pt private
Run config in ptree.
Definition at line 63 of file SimBuilder.h.
Referenced by Build(), ReadAgeContactPtree(), and ReadDiseasePtree().
The documentation for this class was generated from the following files:
SimBuilder.h
SimBuilder.cpp