Stride Reference Manual: stride::LocationDataConfig Class Reference
stride::LocationDataConfig Class Reference
#include <LocationData.h>
Public Member Functions
size_t GetSize () const
Static Public Member Functions
static LocationDataConfig GetConfig ()
Private Member Functions
LocationDataConfig ()=default
template<typename T >
void RegisterLocationData (LocationData< T > *locationData)
template<typename T >
void DeregisterLocationData (LocationData< T > *locationData)
Private Attributes
bool locked = false
size_t size = 0
std::set< void * > registeredLocationData {}
Friends
template<typename T >
class LocationData
Detailed Description
Definition at line 16 of file LocationData.h.
Constructor & Destructor Documentation
LocationDataConfig()
stride::LocationDataConfig::LocationDataConfig () private default
Member Function Documentation
GetSize()
size_t stride::LocationDataConfig::GetSize () const inline
Definition at line 30 of file LocationData.h.
References size.
GetConfig()
static LocationDataConfig stride::LocationDataConfig::GetConfig () inline static
Definition at line 34 of file LocationData.h.
Referenced by stride::LocationData< std::vector< unsigned int > >::LocationData(), and stride::LocationData< std::vector< unsigned int > >::~LocationData().
RegisterLocationData()
template<typename T > void stride::LocationDataConfig::RegisterLocationData (LocationData< T > * locationData) inline private
Definition at line 51 of file LocationData.h.
References registeredLocationData.
Referenced by stride::LocationData< std::vector< unsigned int > >::LocationData().
DeregisterLocationData()
template<typename T > void stride::LocationDataConfig::DeregisterLocationData (LocationData< T > * locationData) inline private
Definition at line 56 of file LocationData.h.
References registeredLocationData.
Referenced by stride::LocationData< std::vector< unsigned int > >::~LocationData().
Friends And Related Function Documentation
LocationData
template<typename T > friend class LocationData friend
Definition at line 44 of file LocationData.h.
Member Data Documentation
locked
bool stride::LocationDataConfig::locked = false private
Definition at line 46 of file LocationData.h.
size
size_t stride::LocationDataConfig::size = 0 private
Definition at line 47 of file LocationData.h.
Referenced by GetSize().
registeredLocationData
std::set<void*> stride::LocationDataConfig::registeredLocationData {} private
Definition at line 49 of file LocationData.h.
Referenced by DeregisterLocationData(), and RegisterLocationData().
The documentation for this class was generated from the following file:
LocationData.h