Stride Reference Manual: stride::TravelTable Class Reference
stride::TravelTable Class Reference
class to store travel info in the form of beans these beans can be sequentially updated once per simulation day
#include <TravelTable.h>
Public Member Functions
TravelTable (std::shared_ptr< stride::MultiPopulation > pop)
constructor for the travel table
bool Travel (stride::Person *, size_t index)
randomly choose to travel or not
unsigned int ChooseTravelLocation (GridPoolType::Id type, size_t index)
Choose a location to travel to randomly.
unsigned int GetSize () const
Get Size of table.
void Update ()
update all beans in the table if a beans time reaches 0, reset the person's pool and remove the bean from the list
void AddBean (stride::Person *, TravelType)
add bean to the table
Private Attributes
std::vector< TravelBean > beans
beans inside the table list of beans containing travel information for each person
std::shared_ptr< stride::MultiPopulation > multipop
pointer to the multipopulation used to choose a location to travel to
std::function< int()> generator
generator for travel used to choose who travels and who doesn't
std::function< int()> typegenerator
generator for travel type used to choose between business type and vacation type if it is necessary for the person profile
Detailed Description
class to store travel info in the form of beans these beans can be sequentially updated once per simulation day
Definition at line 66 of file TravelTable.h.
Constructor & Destructor Documentation
TravelTable()
stride::TravelTable::TravelTable (std::shared_ptr< stride::MultiPopulation > pop) explicit
constructor for the travel table
Parameters
multipopulation object to simulate travel for
Definition at line 123 of file TravelTable.cpp.
References generator, multipop, stride::TravelBean::SetBusinessTime(), stride::TravelBean::SetVacationTime(), and typegenerator.
Member Function Documentation
Travel()
bool stride::TravelTable::Travel (stride::Person * p, size_t index)
randomly choose to travel or not
Definition at line 31 of file TravelTable.cpp.
References stride::BUSINESS, stride::Person::m_is_traveling, stride::Person::m_pool_ids, stride::Person::m_travel_pool_type, stride::GridPoolType::PrimaryCommunity, stride::ContactPoolType::PrimaryCommunity, stride::VACATION, stride::ContactPoolType::Work, and stride::GridPoolType::Workplace.
ChooseTravelLocation()
unsigned int stride::TravelTable::ChooseTravelLocation (GridPoolType::Id type, size_t index)
Choose a location to travel to randomly.
calculate grids to choose from
throw exception if size is 0
return random pool if 1 grid
calculate distribution for grid choice
choose grid
get random pool id of type from grid
Definition at line 58 of file TravelTable.cpp.
References stride::util::RNManager::GetGenerator().
GetSize()
unsigned int stride::TravelTable::GetSize () const inline
Get Size of table.
Definition at line 94 of file TravelTable.h.
References beans.
Update()
void stride::TravelTable::Update ()
update all beans in the table if a beans time reaches 0, reset the person's pool and remove the bean from the list
Definition at line 101 of file TravelTable.cpp.
References stride::Person::m_pool_ids, stride::TravelBean::person_ptr, stride::TravelBean::pool_id, and stride::TravelBean::time.
AddBean()
void stride::TravelTable::AddBean (stride::Person * p, stride::TravelType t)
add bean to the table
Definition at line 26 of file TravelTable.cpp.
Member Data Documentation
beans
std::vector<TravelBean> stride::TravelTable::beans private
beans inside the table list of beans containing travel information for each person
Definition at line 71 of file TravelTable.h.
Referenced by GetSize().
multipop
std::shared_ptr<stride::MultiPopulation> stride::TravelTable::multipop private
pointer to the multipopulation used to choose a location to travel to
Definition at line 74 of file TravelTable.h.
Referenced by TravelTable().
generator
std::function<int()> stride::TravelTable::generator private
generator for travel used to choose who travels and who doesn't
Definition at line 77 of file TravelTable.h.
Referenced by TravelTable().
typegenerator
std::function<int()> stride::TravelTable::typegenerator private
generator for travel type used to choose between business type and vacation type if it is necessary for the person profile
Definition at line 80 of file TravelTable.h.
Referenced by TravelTable().
The documentation for this class was generated from the following files:
TravelTable.h
TravelTable.cpp