Stride Reference Manual: stride::MultiPopulation Class Reference
stride::MultiPopulation Class Reference
data structure to keep multiple populations and their names consisting of 1 main grid with multiple locations a number of grids that have a concentrated population in 1 location
#include <MultiPopulation.h>
Public Member Functions
MultiPopulation ()
initialize empty
MultiPopulation (boost::property_tree::ptree)
initialize all populations with config file this will create a number of grids and concatenate the same population, as to preserve a single population
std::shared_ptr< stride::Population > Get () const
return the generated population object
void LogToFile (boost::filesystem::path path)
log the multipop to a file
const std::vector< std::shared_ptr< stride::GeoGrid > > & GetGrids () const
simple getters for multipop attributes
const std::vector< std::string > & GetNames () const
const std::vector< unsigned long > & GetIndices () const
std::shared_ptr< stride::GeoGrid > GetCombinedGrid () const
Get combined grid of all grids in the grids list this concatenates all vector properties of the grids.
boost::property_tree::ptree GetConfig () const
return the config (for use in travel table mainly)
Private Member Functions
void Config (boost::property_tree::ptree)
initialize the multipop config
void InitMainGrid ()
create the main population
void InitSideGrid (unsigned int i)
create a side population that is represented as if it is a point
Private Attributes
std::shared_ptr< stride::Population > m_pop
total population object to simulate with
std::vector< std::shared_ptr< stride::GeoGrid > > m_grids
list of grids created this consists of 1 grid with possibly multiple locations and 1 or more grids with 1 location (as if it is a point)
std::vector< std::string > m_regionNames
list of all region names (only side regions ex: Frankrijk,...)
std::vector< unsigned long > m_indices
list of starting indexes for all subpopulations within the m_pop object
boost::property_tree::ptree m_multipopConfig
config of the multiple populations this is cached for use within initialization
Detailed Description
data structure to keep multiple populations and their names consisting of 1 main grid with multiple locations a number of grids that have a concentrated population in 1 location
Definition at line 20 of file MultiPopulation.h.
Constructor & Destructor Documentation
MultiPopulation() [1/2]
stride::MultiPopulation::MultiPopulation () default
initialize empty
MultiPopulation() [2/2]
stride::MultiPopulation::MultiPopulation (boost::property_tree::ptree configPt) explicit
initialize all populations with config file this will create a number of grids and concatenate the same population, as to preserve a single population
initialize all populations with config file
Definition at line 12 of file MultiPopulation.cpp.
References Config(), InitMainGrid(), InitSideGrid(), and m_multipopConfig.
Member Function Documentation
Get()
std::shared_ptr< stride::Population > stride::MultiPopulation::Get () const
return the generated population object
Definition at line 64 of file MultiPopulation.cpp.
LogToFile()
void stride::MultiPopulation::LogToFile (boost::filesystem::path path)
log the multipop to a file
Definition at line 66 of file MultiPopulation.cpp.
References stride::ContactPoolType::Household, stride::ContactPoolType::PrimaryCommunity, stride::ContactPoolType::School, stride::ContactPoolType::SecondaryCommunity, and stride::ContactPoolType::Work.
GetGrids()
const std::vector< std::shared_ptr< stride::GeoGrid > > & stride::MultiPopulation::GetGrids () const
simple getters for multipop attributes
Definition at line 58 of file MultiPopulation.cpp.
GetNames()
const std::vector< std::string > & stride::MultiPopulation::GetNames () const
Definition at line 60 of file MultiPopulation.cpp.
GetIndices()
const std::vector< unsigned long > & stride::MultiPopulation::GetIndices () const
Definition at line 62 of file MultiPopulation.cpp.
GetCombinedGrid()
std::shared_ptr< stride::GeoGrid > stride::MultiPopulation::GetCombinedGrid () const
Get combined grid of all grids in the grids list this concatenates all vector properties of the grids.
Definition at line 88 of file MultiPopulation.cpp.
References stride::GridPoolType::Academy, stride::GridPoolType::PrimaryCommunity, stride::GridPoolType::School, stride::GridPoolType::SecondaryCommunity, and stride::GridPoolType::Workplace.
GetConfig()
boost::property_tree::ptree stride::MultiPopulation::GetConfig () const inline
return the config (for use in travel table mainly)
Definition at line 45 of file MultiPopulation.h.
References m_multipopConfig.
Config()
void stride::MultiPopulation::Config (boost::property_tree::ptree configPt) private
initialize the multipop config
Definition at line 26 of file MultiPopulation.cpp.
Referenced by MultiPopulation().
InitMainGrid()
void stride::MultiPopulation::InitMainGrid () private
create the main population
Definition at line 29 of file MultiPopulation.cpp.
References stride::Population::Create(), and stride::Population::CreateEmpty().
Referenced by MultiPopulation().
InitSideGrid()
void stride::MultiPopulation::InitSideGrid (unsigned int i) private
create a side population that is represented as if it is a point
create a side population
Definition at line 40 of file MultiPopulation.cpp.
References stride::Population::Create(), and stride::GridPoolType::SecondaryCommunity.
Referenced by MultiPopulation().
Member Data Documentation
m_pop
std::shared_ptr<stride::Population> stride::MultiPopulation::m_pop private
total population object to simulate with
Definition at line 49 of file MultiPopulation.h.
m_grids
std::vector<std::shared_ptr<stride::GeoGrid> > stride::MultiPopulation::m_grids private
list of grids created this consists of 1 grid with possibly multiple locations and 1 or more grids with 1 location (as if it is a point)
Definition at line 54 of file MultiPopulation.h.
m_regionNames
std::vector<std::string> stride::MultiPopulation::m_regionNames private
list of all region names (only side regions ex: Frankrijk,...)
Definition at line 57 of file MultiPopulation.h.
m_indices
std::vector<unsigned long> stride::MultiPopulation::m_indices private
list of starting indexes for all subpopulations within the m_pop object
Definition at line 61 of file MultiPopulation.h.
m_multipopConfig
boost::property_tree::ptree stride::MultiPopulation::m_multipopConfig private
config of the multiple populations this is cached for use within initialization
Definition at line 65 of file MultiPopulation.h.
Referenced by GetConfig(), and MultiPopulation().
The documentation for this class was generated from the following files:
MultiPopulation.h
MultiPopulation.cpp