Stride Reference Manual: stride::SurveySeeder Class Reference
stride::SurveySeeder Class Reference
Seeds the population with survey participants.
#include <SurveySeeder.h>
Public Member Functions
SurveySeeder (const boost::property_tree::ptree &configPt, util::RNManager &rnManager)
Initialize Seeder.
std::shared_ptr< Population > Seed (std::shared_ptr< Population > pop)
Seeds the population with survey participants.
Private Attributes
const boost::property_tree::ptree & m_config_pt
Run config.
util::RNManager & m_rn_manager
Random number manager.
Detailed Description
Seeds the population with survey participants.
Definition at line 34 of file SurveySeeder.h.
Constructor & Destructor Documentation
SurveySeeder()
stride::SurveySeeder::SurveySeeder (const boost::property_tree::ptree & configPt, util::RNManager & rnManager)
Initialize Seeder.
Parameters
configPt Configuration parameters.
rnManager Random number manager.
Definition at line 34 of file SurveySeeder.cpp.
Member Function Documentation
Seed()
shared_ptr< Population > stride::SurveySeeder::Seed (std::shared_ptr< Population > pop)
Seeds the population with survey participants.
Parameters
pop Population.
Definition at line 38 of file SurveySeeder.cpp.
References stride::Person::GetAge(), stride::Population::GetContactLogger(), stride::Person::GetGender(), stride::util::RNManager::GetGenerator(), stride::Person::GetId(), stride::Person::GetPoolId(), stride::Person::IsSurveyParticipant(), m_config_pt, m_rn_manager, stride::Person::ParticipateInSurvey(), and stride::util::SegmentedVector< T, N, Safe >::size().
Referenced by stride::PopBuilder::Build().
Member Data Documentation
m_config_pt
const boost::property_tree::ptree& stride::SurveySeeder::m_config_pt private
Run config.
Definition at line 47 of file SurveySeeder.h.
Referenced by Seed().
m_rn_manager
util::RNManager& stride::SurveySeeder::m_rn_manager private
Random number manager.
Definition at line 48 of file SurveySeeder.h.
Referenced by Seed().
The documentation for this class was generated from the following files:
SurveySeeder.h
SurveySeeder.cpp