Stride Reference Manual: stride::GeoGridBuilder Class Reference
stride::GeoGridBuilder Class Reference
#include <GeoGridBuilder.h>
Public Member Functions
GeoGridBuilder (std::shared_ptr< boost::property_tree::ptree > config, std::shared_ptr< util::RNManager > rn_manager, unsigned requested_population, std::shared_ptr< GeoGrid > geogrid)
constructor
void PlaceSites (GridPoolType::Id siteType, unsigned requiredCapacity)
place sites in grid of a type, given a required capacity
void GenerateDistricts (unsigned int minfrac, double a, double b, double c)
Split grid loations up in various districts.
Private Member Functions
void ReadLocations ()
Reads location data from cities csv.
void ReadCommuting ()
Reads commuting values from commuting csv.
void CalculateCommutingPopulations ()
Calculate the populations of each location when considering commuters.
void ScalePopulation (unsigned requested_population)
void ReadCapacities ()
Reads the capacities of the sites and contact pools from config.
locationData< unsigned int > PlaceSites (const stride::locationData< unsigned > &distribution, unsigned int requestedSitesAmount)
place sites in grid of a type, given a required capacity
bool GetsFractured (unsigned int population, unsigned int minfrac, std::function< double(double)> func)
Determines if location with given population gets fractured into several districts.
trng::fast_discrete_dist NumberDistrictsDist (unsigned int pop, unsigned int minfrac)
returns a distribution 'dist' of size n where dist[i] is probability of being split up into i+1 fractions for a given population size
std::vector< unsigned int > GetDistrictPopulations (const unsigned int &amountOfFracs, const unsigned long &pop)
generates vector containing 'amountOfFracs' new populations for the new locations
void AddDistrict (unsigned int locationIndex, unsigned int newid, std::string newname, unsigned int newpop)
add district to grid as new location.
Private Attributes
std::shared_ptr< GeoGrid > m_grid
shared pointer to grid
std::shared_ptr< boost::property_tree::ptree > config
pointer to configuration ptree
std::shared_ptr< util::RNManager > rn_manager
pointer to random number manager
Detailed Description
Definition at line 27 of file GeoGridBuilder.h.
Constructor & Destructor Documentation
GeoGridBuilder()
stride::GeoGridBuilder::GeoGridBuilder (std::shared_ptr< boost::property_tree::ptree > config, std::shared_ptr< util::RNManager > rn_manager, unsigned requested_population, std::shared_ptr< GeoGrid > geogrid)
constructor
Definition at line 12 of file GeoGridBuilder.cpp.
Member Function Documentation
PlaceSites() [1/2]
void stride::GeoGridBuilder::PlaceSites (GridPoolType::Id siteType, unsigned requiredCapacity)
place sites in grid of a type, given a required capacity
Parameters
siteType type for which to places sites in grid
requiredCapacity capacity of sites
GenerateDistricts()
void stride::GeoGridBuilder::GenerateDistricts (unsigned int minfrac, double a, double b, double c)
Split grid loations up in various districts.
Parameters
minfrac minimum size of resulting district
a parameter used in determining size of districts
b parameter used in determining size of districts
c parameter used in determining size of districts
Definition at line 259 of file GeoGridBuilder.cpp.
ReadLocations()
void stride::GeoGridBuilder::ReadLocations () private
Reads location data from cities csv.
Uses filename from config.
Definition at line 42 of file GeoGridBuilder.cpp.
References stride::util::FileSys::GetDataDir().
ReadCommuting()
void stride::GeoGridBuilder::ReadCommuting () private
Reads commuting values from commuting csv.
Uses filename from config.
Definition at line 64 of file GeoGridBuilder.cpp.
References stride::util::FileSys::GetDataDir(), and stride::util::CSV::GetLabels().
CalculateCommutingPopulations()
void stride::GeoGridBuilder::CalculateCommutingPopulations () private
Calculate the populations of each location when considering commuters.
Definition at line 100 of file GeoGridBuilder.cpp.
ScalePopulation()
void stride::GeoGridBuilder::ScalePopulation (unsigned requested_population) private
Definition at line 142 of file GeoGridBuilder.cpp.
ReadCapacities()
void stride::GeoGridBuilder::ReadCapacities () private
Reads the capacities of the sites and contact pools from config.
These capacities are the expected amount of people in a site/contact pool.
Definition at line 163 of file GeoGridBuilder.cpp.
References stride::GridPoolType::Academy, stride::GridPoolType::PrimaryCommunity, stride::GridPoolType::School, stride::GridPoolType::SecondaryCommunity, and stride::GridPoolType::Workplace.
PlaceSites() [2/2]
stride::locationData< unsigned int > stride::GeoGridBuilder::PlaceSites (const stride::locationData< unsigned > & distribution, unsigned int requestedSitesAmount) private
place sites in grid of a type, given a required capacity
Definition at line 189 of file GeoGridBuilder.cpp.
GetsFractured()
bool stride::GeoGridBuilder::GetsFractured (unsigned int population, unsigned int minfrac, std::function< double(double)> func) private
Determines if location with given population gets fractured into several districts.
Parameters
population population of location
minfrac minimum population for a location to be fractured function that returns value between 0 and 1 for positive integers that represents probablity of being fractured
Returns
bool indicated whether or not location has to be split up
Definition at line 244 of file GeoGridBuilder.cpp.
NumberDistrictsDist()
trng::fast_discrete_dist stride::GeoGridBuilder::NumberDistrictsDist (unsigned int pop, unsigned int minfrac) private
returns a distribution 'dist' of size n where dist[i] is probability of being split up into i+1 fractions for a given population size
Parameters
pop size of population
minfrac minimum size of district
distribution used to determine how in how many fractions city will be divided.
Definition at line 301 of file GeoGridBuilder.cpp.
GetDistrictPopulations()
std::vector< unsigned int > stride::GeoGridBuilder::GetDistrictPopulations (const unsigned int & amountOfFracs, const unsigned long & pop) private
generates vector containing 'amountOfFracs' new populations for the new locations
stop population from going under negative
Definition at line 317 of file GeoGridBuilder.cpp.
AddDistrict()
void stride::GeoGridBuilder::AddDistrict (unsigned int locationIndex, unsigned int newid, std::string newname, unsigned int newpop) private
add district to grid as new location.
New location will have same province, coordinates as original location (of which it is a district)
Parameters
locationIndex index of original location
newid ID for new location
newname name for new location
newpop new population size for location
Definition at line 342 of file GeoGridBuilder.cpp.
Member Data Documentation
m_grid
std::shared_ptr<GeoGrid> stride::GeoGridBuilder::m_grid private
shared pointer to grid
Definition at line 86 of file GeoGridBuilder.h.
config
std::shared_ptr<boost::property_tree::ptree> stride::GeoGridBuilder::config private
pointer to configuration ptree
Definition at line 87 of file GeoGridBuilder.h.
rn_manager
std::shared_ptr<util::RNManager> stride::GeoGridBuilder::rn_manager private
pointer to random number manager
Definition at line 88 of file GeoGridBuilder.h.
The documentation for this class was generated from the following files:
GeoGridBuilder.h
GeoGridBuilder.cpp