Stride Reference Manual: stride::qt::QCommuting Class Reference
stride::qt::QCommuting Class Reference
Represents a commuting line that can be drawn on the Map.
#include <QCommuting.h>
Public Member Functions
QCommuting (double fromX, double fromY, double toX, double toY, double comValue, unsigned fromLoc, unsigned toLoc, double percentage, std::shared_ptr< stride::GeoGrid > grid, QColor color=Qt::black, double radius=10.0)
Constructor.
~QCommuting () override=default
Destructor.
void Draw (QPainter &painter) const override
Draws the commuting way.
const QPointF & GetToPoint () const
Get the pixel of the to Location on the Map.
const unsigned GetFromLocation () const
Get a pointer to the from Location (~start point).
const unsigned GetToLocation () const
Get a pointer to the to Location (~end point).
bool operator== (const QCommuting &other) const
== Operator-overloading.
Public Member Functions inherited from stride::qt::QDrawable
QDrawable ()=default
Default Constructor.
QDrawable (double x, double y, QColor color=Qt::red, double radius=20.0)
Constructor.
~QDrawable () override=default
Destructor.
const QPointF & GetPoint () const
Get the pixel of this object on the Map.
const QColor & GetColor () const
Get the color of the object drawn on the Map for this site.
virtual const QString GetTooltipText () const
Get the tooltip information that needs to be displayed whenever the user hovers over this object.
double GetRadius () const
Get the radius of the point of this object.
void SetSelected (bool select)
(Un)select the object
void SetVisibility (bool vis)
Set the visibility of the object.
bool IsVisible () const
Check if the object is visible (invisible if filtered out).
Private Attributes
QPointF toPoint
The pixel on the Map of the to Location.
unsigned fromLocation
The from Location.
unsigned toLocation
The to Location.
double value
The commuting value between the two locations.
std::shared_ptr< stride::GeoGrid > geoGrid
The GeoGrid object.
Additional Inherited Members
Protected Attributes inherited from stride::qt::QDrawable
QColor color
The color of the object.
QPointF point
The pixel on the Map.
double radius
The radius of the object (in pixels).
QString tooltipText
The tooltip information.
bool selected
Check if the user has selected this object.
bool visible
Check if the object is visible (invisible if filtered out).
Detailed Description
Represents a commuting line that can be drawn on the Map.
Definition at line 17 of file QCommuting.h.
Constructor & Destructor Documentation
QCommuting()
stride::qt::QCommuting::QCommuting (double fromX, double fromY, double toX, double toY, double comValue, unsigned fromLoc, unsigned toLoc, double percentage, std::shared_ptr< stride::GeoGrid > grid, QColor color = Qt::black, double radius = 10.0)
Constructor.
Parameters
fromX The x pixel of the from location relative to the Map.
fromY The y pixel of the from location relative to the Map.
toX The x pixel of the to location relative to the Map.
toY The y pixel of the to location relative to the Map.
comValue The commuting value between those points.
fromLoc The from location (the start of the commuting).
toLoc The to location (the end of the commuting).
percentage The ratio of this commuting value on the largest commuting value (used to calculate the radius).
grid The GeoGrid object which contains the entire information.
color (optional) The color of the line drawn on the Map for this site.
radius (optional) The radius of the line drawn on the Map for this site.
Definition at line 7 of file QCommuting.cpp.
References fromLocation, geoGrid, stride::qt::QDrawable::radius, toLocation, stride::qt::QDrawable::tooltipText, and value.
~QCommuting()
stride::qt::QCommuting::~QCommuting () override default
Destructor.
Member Function Documentation
Draw()
void stride::qt::QCommuting::Draw (QPainter & painter) const override virtual
Draws the commuting way.
Parameters
painter The painter that will be used.
Implements stride::qt::QDrawable.
Definition at line 24 of file QCommuting.cpp.
References stride::qt::QDrawable::GetColor(), stride::qt::QDrawable::GetPoint(), stride::qt::QDrawable::GetRadius(), GetToPoint(), and stride::qt::QDrawable::visible.
GetToPoint()
const QPointF & stride::qt::QCommuting::GetToPoint () const
Get the pixel of the to Location on the Map.
Returns
The QPoint of the to Location. (the pixel on the map)
Definition at line 36 of file QCommuting.cpp.
References toPoint.
Referenced by Draw().
GetFromLocation()
const unsigned stride::qt::QCommuting::GetFromLocation () const
Get a pointer to the from Location (~start point).
Returns
The Location.
Definition at line 38 of file QCommuting.cpp.
References fromLocation.
Referenced by operator==().
GetToLocation()
const unsigned stride::qt::QCommuting::GetToLocation () const
Get a pointer to the to Location (~end point).
Returns
The Location.
Definition at line 40 of file QCommuting.cpp.
References toLocation.
Referenced by operator==().
operator==()
bool stride::qt::QCommuting::operator== (const QCommuting & other) const
== Operator-overloading.
Parameters
other Other QLocation that needs to be compared.
Returns
True if equal.
Definition at line 42 of file QCommuting.cpp.
References GetFromLocation(), and GetToLocation().
Member Data Documentation
toPoint
QPointF stride::qt::QCommuting::toPoint private
The pixel on the Map of the to Location.
Definition at line 64 of file QCommuting.h.
Referenced by GetToPoint().
fromLocation
unsigned stride::qt::QCommuting::fromLocation private
The from Location.
Definition at line 65 of file QCommuting.h.
Referenced by GetFromLocation(), and QCommuting().
toLocation
unsigned stride::qt::QCommuting::toLocation private
The to Location.
Definition at line 66 of file QCommuting.h.
Referenced by GetToLocation(), and QCommuting().
value
double stride::qt::QCommuting::value private
The commuting value between the two locations.
Definition at line 67 of file QCommuting.h.
Referenced by QCommuting().
geoGrid
std::shared_ptr<stride::GeoGrid> stride::qt::QCommuting::geoGrid private
The GeoGrid object.
Definition at line 69 of file QCommuting.h.
Referenced by QCommuting().
The documentation for this class was generated from the following files:
QCommuting.h
QCommuting.cpp