Stride Reference Manual: stride::qt::Stats Class Reference
stride::qt::Stats Class Reference
Handles all the statistics of the geogrid en popgen: shows and saves charts.
#include <Stats.h>
Public Slots
void HouseholdStats ()
Show the household size distribution.
void WorkplaceStats ()
Show the workplace size distribution.
void AgeStats ()
Show the age distribution.
void CitiesStats ()
Show the cities distribution.
void SaveChart ()
Save the current chart in the window.
void SaveData ()
Save the raw data of the chart as a csv file.
Public Member Functions
Stats (std::shared_ptr< stride::GeoGrid > _grid, boost::property_tree::ptree *config)
Constructor.
~Stats ()=default
Default destructor.
Private Member Functions
void BuildBarChart (const QString &title, const std::map< unsigned, qreal > &dist, qreal min, qreal max, const QString &xTitle="Size", const QString &yTitle="Amount")
Build and show a bar chart.
void BuildBoxPlot (const QString &title, std::vector< qreal > &values, const QString &yTitle="Amount")
Build and show a boxplot.
qreal FindMedian (const std::vector< qreal > &list, int begin, int end)
Get the median value within a range.
Private Attributes
std::shared_ptr< stride::GeoGrid > grid
The GeoGrid object which contains the entire information.
std::shared_ptr< stride::Population > pop
The population.
boost::property_tree::ptree * config_run
Simulation configuration.
QChartView * chartView
The current chart view in the window.
std::pair< std::vector< std::string >, std::vector< std::vector< int > > > data
Raw data of the chart.
Detailed Description
Handles all the statistics of the geogrid en popgen: shows and saves charts.
Following stats are supported now:
The size of households.
The size of workplaces.
The age of the population.
The population of cities.
Definition at line 42 of file Stats.h.
Constructor & Destructor Documentation
Stats()
stride::qt::Stats::Stats (std::shared_ptr< stride::GeoGrid > _grid, boost::property_tree::ptree * config)
Constructor.
Parameters
_grid The geogrid.
_popgen The population generator. config The configuration of the simulation.
Definition at line 11 of file Stats.cpp.
References grid, pop, SaveChart(), and SaveData().
~Stats()
stride::qt::Stats::~Stats () default
Default destructor.
Member Function Documentation
HouseholdStats
void stride::qt::Stats::HouseholdStats () slot
Show the household size distribution.
Definition at line 24 of file Stats.cpp.
References BuildBarChart(), and grid.
Referenced by stride::qt::Window::SetStats().
WorkplaceStats
void stride::qt::Stats::WorkplaceStats () slot
Show the workplace size distribution.
Definition at line 50 of file Stats.cpp.
References BuildBarChart(), and grid.
Referenced by stride::qt::Window::SetStats().
AgeStats
void stride::qt::Stats::AgeStats () slot
Show the age distribution.
Definition at line 83 of file Stats.cpp.
References BuildBarChart(), and pop.
Referenced by stride::qt::Window::SetStats().
CitiesStats
void stride::qt::Stats::CitiesStats () slot
Show the cities distribution.
Definition at line 108 of file Stats.cpp.
References BuildBoxPlot(), and grid.
Referenced by stride::qt::Window::SetStats().
SaveChart
void stride::qt::Stats::SaveChart () slot
Save the current chart in the window.
Definition at line 240 of file Stats.cpp.
References chartView, config_run, and stride::util::FileSys::GetCurrentDir().
Referenced by Stats().
SaveData
void stride::qt::Stats::SaveData () slot
Save the raw data of the chart as a csv file.
Definition at line 255 of file Stats.cpp.
References chartView, config_run, data, and stride::util::FileSys::GetCurrentDir().
Referenced by Stats().
BuildBarChart()
void stride::qt::Stats::BuildBarChart (const QString & title, const std::map< unsigned, qreal > & dist, qreal min, qreal max, const QString & xTitle = "Size", const QString & yTitle = "Amount") private
Build and show a bar chart.
Parameters
title Title of the chart.
dist The distribution.
min The min value in the dist.
max The max value in the dist.
xTitle The title of the x axis.
yTitle The title of the y axis.
Definition at line 119 of file Stats.cpp.
References chartView, and data.
Referenced by AgeStats(), HouseholdStats(), and WorkplaceStats().
BuildBoxPlot()
void stride::qt::Stats::BuildBoxPlot (const QString & title, std::vector< qreal > & values, const QString & yTitle = "Amount") private
Build and show a boxplot.
Parameters
title Title of the chart.
values All the values used for the boxplot, list will be sorted afterwards.
yTitle The title of the y axis.
Definition at line 176 of file Stats.cpp.
References chartView, data, and FindMedian().
Referenced by CitiesStats().
FindMedian()
qreal stride::qt::Stats::FindMedian (const std::vector< qreal > & list, int begin, int end) private
Get the median value within a range.
source: https://doc.qt.io/qt-5.10/qtcharts-boxplotchart-boxdatareader-cpp.html
Parameters
list The sorted list.
begin The start of the range.
end The end of the range.
Returns
The median.
Definition at line 226 of file Stats.cpp.
Referenced by BuildBoxPlot().
Member Data Documentation
grid
std::shared_ptr<stride::GeoGrid> stride::qt::Stats::grid private
The GeoGrid object which contains the entire information.
Definition at line 100 of file Stats.h.
Referenced by CitiesStats(), HouseholdStats(), Stats(), and WorkplaceStats().
pop
std::shared_ptr<stride::Population> stride::qt::Stats::pop private
The population.
Definition at line 101 of file Stats.h.
Referenced by AgeStats(), and Stats().
config_run
boost::property_tree::ptree* stride::qt::Stats::config_run private
Simulation configuration.
Definition at line 103 of file Stats.h.
Referenced by SaveChart(), and SaveData().
chartView
QChartView* stride::qt::Stats::chartView private
The current chart view in the window.
Definition at line 105 of file Stats.h.
Referenced by BuildBarChart(), BuildBoxPlot(), SaveChart(), and SaveData().
data
std::pair<std::vector<std::string>, std::vector<std::vector<int> > > stride::qt::Stats::data private
Raw data of the chart.
Definition at line 107 of file Stats.h.
Referenced by BuildBarChart(), BuildBoxPlot(), and SaveData().
The documentation for this class was generated from the following files:
Stats.h
Stats.cpp