Stride Reference Manual: stride::util::Any Class Reference
stride::util::Any Class Reference
A RAII void*, for type erasure, that can point to anything.
#include <Any.h>
Public Member Functions
Any ()
~Any ()
Any (const Any &)=delete
Any & operator= (const Any &)=delete
Any (Any &&)=delete
Any & operator= (Any &&)=delete
template<typename T , class... Args>
void emplace (Args &&... args)
template<typename T >
T * cast () const
operator bool () const
Private Attributes
void * m_ptr
std::function< void()> m_destroy
Detailed Description
A RAII void*, for type erasure, that can point to anything.
Any owns the pointer, and cleans up with a custom destructor. Does type verification when NDEBUG is not set.
Definition at line 36 of file Any.h.
Constructor & Destructor Documentation
Any() [1/3]
stride::util::Any::Any () inline
Definition at line 40 of file Any.h.
~Any()
stride::util::Any::~Any () inline
Definition at line 50 of file Any.h.
References m_destroy.
Any() [2/3]
stride::util::Any::Any (const Any &) delete
Any() [3/3]
stride::util::Any::Any (Any &&) delete
Member Function Documentation
operator=() [1/2]
Any& stride::util::Any::operator= (const Any &) delete
operator=() [2/2]
Any& stride::util::Any::operator= (Any &&) delete
emplace()
template<typename T , class... Args> void stride::util::Any::emplace (Args &&... args) inline
Definition at line 60 of file Any.h.
References m_destroy, and m_ptr.
Referenced by stride::Population::InitBeliefPolicy().
cast()
template<typename T > T* stride::util::Any::cast () const inline
Definition at line 72 of file Any.h.
References m_ptr.
Referenced by stride::Population::SetBeliefPolicy().
operator bool()
stride::util::Any::operator bool () const inline explicit
Definition at line 86 of file Any.h.
References m_ptr.
Member Data Documentation
m_ptr
void* stride::util::Any::m_ptr private
Definition at line 89 of file Any.h.
Referenced by cast(), emplace(), and operator bool().
m_destroy
std::function<void()> stride::util::Any::m_destroy private
Definition at line 90 of file Any.h.
Referenced by emplace(), and ~Any().
The documentation for this class was generated from the following file:
Any.h