Stride Reference Manual: stride::PopBuilder Class Reference
stride::PopBuilder Class Reference
Initializes Population objects.
#include <PopBuilder.h>
Public Member Functions
PopBuilder (const boost::property_tree::ptree &configPt, util::RNManager &rnManager)
Initializing constructor.
std::shared_ptr< Population > Build (std::shared_ptr< Population > pop)
Build Population and return it afterwards.
std::shared_ptr< Population > Build (std::shared_ptr< GeoGrid > grid, const unsigned popNr=0)
Construct geogrid and population inside it.
std::shared_ptr< Population > BuildFromFile (std::shared_ptr< GeoGrid > grid, const std::string dirname, const unsigned popNr=0)
Private Member Functions
std::shared_ptr< Population > MakePoolSys (std::shared_ptr< Population > pop)
Fills up pop's contact pool system and return pop.
std::shared_ptr< Population > MakePersons (std::shared_ptr< Population > pop)
Generates pop's individuals and return pop.
Private Attributes
const boost::property_tree::ptree & m_config_pt
Configuration property tree.
util::RNManager & m_rn_manager
Random numbere generation management.
Detailed Description
Initializes Population objects.
Definition at line 36 of file PopBuilder.h.
Constructor & Destructor Documentation
PopBuilder()
stride::PopBuilder::PopBuilder (const boost::property_tree::ptree & configPt, util::RNManager & rnManager)
Initializing constructor.
Parameters
configPt Property_tree with general configuration settings.
rnManager Random number manager for pop build process.
Definition at line 35 of file PopBuilder.cpp.
Member Function Documentation
Build() [1/2]
shared_ptr< Population > stride::PopBuilder::Build (std::shared_ptr< Population > pop)
Build Population and return it afterwards.
The steps are:
Check input data.
Read persons from file and instatiate them.
Fill up the various type of contactpools.
Seed the population with contact survey participants.
Definition at line 123 of file PopBuilder.cpp.
References stride::util::FileSys::GetConfigDir(), stride::util::FileSys::GetDataDir(), m_config_pt, m_rn_manager, stride::util::RNManager::Info::m_stream_count, MakePersons(), MakePoolSys(), and stride::SurveySeeder::Seed().
Referenced by stride::Population::Create().
Build() [2/2]
std::shared_ptr< Population > stride::PopBuilder::Build (std::shared_ptr< GeoGrid > grid, const unsigned popNr = 0)
Construct geogrid and population inside it.
Definition at line 174 of file PopBuilder.cpp.
References stride::util::FileSys::GetConfigDir(), stride::util::FileSys::GetDataDir(), m_config_pt, m_rn_manager, stride::util::RNManager::Info::m_stream_count, MakePoolSys(), and stride::SurveySeeder::Seed().
BuildFromFile()
std::shared_ptr<Population> stride::PopBuilder::BuildFromFile (std::shared_ptr< GeoGrid > grid, const std::string dirname, const unsigned popNr = 0)
MakePoolSys()
shared_ptr< Population > stride::PopBuilder::MakePoolSys (std::shared_ptr< Population > pop) private
Fills up pop's contact pool system and return pop.
Definition at line 37 of file PopBuilder.cpp.
References stride::ContactPoolType::IdList.
Referenced by Build().
MakePersons()
shared_ptr< Population > stride::PopBuilder::MakePersons (std::shared_ptr< Population > pop) private
Generates pop's individuals and return pop.
Definition at line 82 of file PopBuilder.cpp.
References stride::util::FileSys::GetDataDir(), m_config_pt, and stride::util::Split().
Referenced by Build().
Member Data Documentation
m_config_pt
const boost::property_tree::ptree& stride::PopBuilder::m_config_pt private
Configuration property tree.
Definition at line 66 of file PopBuilder.h.
Referenced by Build(), and MakePersons().
m_rn_manager
util::RNManager& stride::PopBuilder::m_rn_manager private
Random numbere generation management.
Definition at line 67 of file PopBuilder.h.
Referenced by Build().
The documentation for this class was generated from the following files:
PopBuilder.h
PopBuilder.cpp