Stride Reference Manual: stride::qt::QConfig Class Reference
stride::qt::QConfig Class Reference
FormBuilder: Maintains a form based on the configuration (ptree) of the simulation.
#include <QConfig.h>
Public Slots
void EditConfig ()
Prompt the user with a window where they can edit the config and run and a new simulation.
Public Member Functions
QConfig ()
Default Constructor.
~QConfig ()=default
Destructor.
void SetConfig (const boost::property_tree::ptree &newConfig)
Set the config of the simulation.
void BuildForm (QPushButton *button)
Build a form based on the configuration of the simulation.
void UpdateForm ()
Update the form with the input fields.
boost::property_tree::ptree GetPtree () const
Get the current ptree.
void SaveConfig ()
Ask if the user want to save the current config.
Private Attributes
QFormLayout * form
The config form that can be used to update the config.
boost::property_tree::ptree config
The config stored in a ptree.
QList< std::pair< QLabel *, QLineEdit * > > lines
All the form line edits with label.
QList< std::pair< QLabel *, QComboBox * > > dropdowns
All the form dropdowns with label.
QList< std::pair< QLabel *, QCheckBox * > > buttons
All the form checkboxes with label.
QFont titleFont
Font of the title.
QWidget * formWidget
Widget for the form.
QScrollArea * scrollAreaForm
Scroll area for form.
QPushButton * runSimButton
PushButton to run the simulation.
QVBoxLayout * vlayout
Vertical Layout to separate the config with the sim button.
Detailed Description
FormBuilder: Maintains a form based on the configuration (ptree) of the simulation.
The user can edit this form via the gui.
Definition at line 23 of file QConfig.h.
Constructor & Destructor Documentation
QConfig()
stride::qt::QConfig::QConfig ()
Default Constructor.
Definition at line 7 of file QConfig.cpp.
References config, stride::util::RunConfigManager::Create(), and titleFont.
~QConfig()
stride::qt::QConfig::~QConfig () default
Destructor.
Member Function Documentation
SetConfig()
void stride::qt::QConfig::SetConfig (const boost::property_tree::ptree & newConfig)
Set the config of the simulation.
Parameters
newConfig The ptree corresponding to the config of the simulation.
Definition at line 21 of file QConfig.cpp.
References config.
Referenced by stride::qt::QSim::QSim().
BuildForm()
void stride::qt::QConfig::BuildForm (QPushButton * button)
Build a form based on the configuration of the simulation.
Parameters
button The button that will start the simulation.
Definition at line 39 of file QConfig.cpp.
References buttons, config, dropdowns, form, stride::util::FileSys::GetDataDir(), stride::util::FileSys::GetRootDir(), lines, runSimButton, titleFont, and stride::RNEngineType::ToString().
Referenced by stride::qt::QSim::QSim().
UpdateForm()
void stride::qt::QConfig::UpdateForm ()
Update the form with the input fields.
Definition at line 175 of file QConfig.cpp.
References buttons, config, dropdowns, stride::util::FileSys::GetConfigDir(), and lines.
Referenced by stride::qt::QSim::StartNewSim().
GetPtree()
boost::property_tree::ptree stride::qt::QConfig::GetPtree () const
Get the current ptree.
Returns
The ptree.
Definition at line 238 of file QConfig.cpp.
References config.
Referenced by stride::qt::QSim::StartNewSim().
SaveConfig()
void stride::qt::QConfig::SaveConfig ()
Ask if the user want to save the current config.
Definition at line 240 of file QConfig.cpp.
References config, and stride::util::FileSys::GetCurrentDir().
Referenced by stride::qt::QSim::StartNewSim().
EditConfig
void stride::qt::QConfig::EditConfig () slot
Prompt the user with a window where they can edit the config and run and a new simulation.
Definition at line 257 of file QConfig.cpp.
References form, formWidget, runSimButton, scrollAreaForm, and vlayout.
Referenced by stride::qt::Window::EditConf().
Member Data Documentation
form
QFormLayout* stride::qt::QConfig::form private
The config form that can be used to update the config.
Definition at line 59 of file QConfig.h.
Referenced by BuildForm(), and EditConfig().
config
boost::property_tree::ptree stride::qt::QConfig::config private
The config stored in a ptree.
Definition at line 60 of file QConfig.h.
Referenced by BuildForm(), GetPtree(), QConfig(), SaveConfig(), SetConfig(), and UpdateForm().
lines
QList<std::pair<QLabel*, QLineEdit*> > stride::qt::QConfig::lines private
All the form line edits with label.
Definition at line 61 of file QConfig.h.
Referenced by BuildForm(), and UpdateForm().
dropdowns
QList<std::pair<QLabel*, QComboBox*> > stride::qt::QConfig::dropdowns private
All the form dropdowns with label.
Definition at line 62 of file QConfig.h.
Referenced by BuildForm(), and UpdateForm().
buttons
QList<std::pair<QLabel*, QCheckBox*> > stride::qt::QConfig::buttons private
All the form checkboxes with label.
Definition at line 63 of file QConfig.h.
Referenced by BuildForm(), and UpdateForm().
titleFont
QFont stride::qt::QConfig::titleFont private
Font of the title.
Definition at line 64 of file QConfig.h.
Referenced by BuildForm(), and QConfig().
formWidget
QWidget* stride::qt::QConfig::formWidget private
Widget for the form.
Definition at line 66 of file QConfig.h.
Referenced by EditConfig().
scrollAreaForm
QScrollArea* stride::qt::QConfig::scrollAreaForm private
Scroll area for form.
Definition at line 67 of file QConfig.h.
Referenced by EditConfig().
runSimButton
QPushButton* stride::qt::QConfig::runSimButton private
PushButton to run the simulation.
Definition at line 68 of file QConfig.h.
Referenced by BuildForm(), and EditConfig().
vlayout
QVBoxLayout* stride::qt::QConfig::vlayout private
Vertical Layout to separate the config with the sim button.
Definition at line 69 of file QConfig.h.
Referenced by EditConfig().
The documentation for this class was generated from the following files:
QConfig.h
QConfig.cpp