Stride Reference Manual: stride::qt::SimReader Class Reference
stride::qt::SimReader Class Reference
Reads the information from the simulator, for example the number of infected people.
#include <SimReader.h>
Public Member Functions
SimReader (boost::filesystem::path path, std::shared_ptr< stride::GeoGrid > grid)
Constructor for postprocessing.
SimReader (std::shared_ptr< Sim > sim, std::shared_ptr< stride::GeoGrid > grid)
Constructor for "live" processing.
unsigned int GetAmountOfInfectedPeopleInLocation (unsigned int locID)
Get number of infected people in the location.
Private Member Functions
void ParseLine (std::string inputLine)
Parse a line from the contact log file: postprocessing.
void SetLocationHasInfected ()
Set the number of infected of the locations.
void SetLocationHasInfectedPostprocess ()
Set the number of infected of the locations: postprocessing.
Private Attributes
const stride::Population * pop
The population.
std::shared_ptr< stride::GeoGrid > geoGrid
The GeoGrid object.
std::vector< unsigned int > m_infectedPeople = {}
List of id's of infected people.
std::map< unsigned, unsigned int > locationHasInfected
Map to link the location to the number of infected people.
Detailed Description
Reads the information from the simulator, for example the number of infected people.
Either from a log file or the simulation directly.
Definition at line 25 of file SimReader.h.
Constructor & Destructor Documentation
SimReader() [1/2]
stride::qt::SimReader::SimReader (boost::filesystem::path path, std::shared_ptr< stride::GeoGrid > grid)
Constructor for postprocessing.
Parameters
path Path to the contact log file
grid The GeoGrid Object
Definition at line 6 of file SimReader.cpp.
References ParseLine(), and SetLocationHasInfectedPostprocess().
SimReader() [2/2]
stride::qt::SimReader::SimReader (std::shared_ptr< Sim > sim, std::shared_ptr< stride::GeoGrid > grid)
Constructor for "live" processing.
Parameters
sim Pointer to the simulator
grid The GeoGrid Object
Definition at line 25 of file SimReader.cpp.
References SetLocationHasInfected().
Member Function Documentation
GetAmountOfInfectedPeopleInLocation()
unsigned int stride::qt::SimReader::GetAmountOfInfectedPeopleInLocation (unsigned int locID)
Get number of infected people in the location.
Parameters
locID The location
Returns
The number of infected people of this location.
Definition at line 40 of file SimReader.cpp.
References locationHasInfected.
Referenced by stride::qt::Map::SetInfectedPeopleLocations().
ParseLine()
void stride::qt::SimReader::ParseLine (std::string inputLine) private
Parse a line from the contact log file: postprocessing.
Definition at line 31 of file SimReader.cpp.
References m_infectedPeople.
Referenced by SimReader().
SetLocationHasInfected()
void stride::qt::SimReader::SetLocationHasInfected () private
Set the number of infected of the locations.
Definition at line 42 of file SimReader.cpp.
References geoGrid, locationHasInfected, and pop.
Referenced by SimReader().
SetLocationHasInfectedPostprocess()
void stride::qt::SimReader::SetLocationHasInfectedPostprocess () private
Set the number of infected of the locations: postprocessing.
Definition at line 52 of file SimReader.cpp.
References geoGrid, locationHasInfected, and m_infectedPeople.
Referenced by SimReader().
Member Data Documentation
pop
const stride::Population* stride::qt::SimReader::pop private
The population.
Definition at line 54 of file SimReader.h.
Referenced by SetLocationHasInfected().
geoGrid
std::shared_ptr<stride::GeoGrid> stride::qt::SimReader::geoGrid private
The GeoGrid object.
Definition at line 55 of file SimReader.h.
Referenced by SetLocationHasInfected(), and SetLocationHasInfectedPostprocess().
m_infectedPeople
std::vector<unsigned int> stride::qt::SimReader::m_infectedPeople = {} private
List of id's of infected people.
Definition at line 56 of file SimReader.h.
Referenced by ParseLine(), and SetLocationHasInfectedPostprocess().
locationHasInfected
std::map<unsigned, unsigned int> stride::qt::SimReader::locationHasInfected private
Map to link the location to the number of infected people.
Definition at line 59 of file SimReader.h.
Referenced by GetAmountOfInfectedPeopleInLocation(), SetLocationHasInfected(), and SetLocationHasInfectedPostprocess().
The documentation for this class was generated from the following files:
SimReader.h
SimReader.cpp