Stride Reference Manual: stride::qttool::Window Class Reference
stride::qttool::Window Class Reference
The main window in the qttool program.
#include <Window.h>
Public Slots
void Save ()
Save the current display to a file.
void SwitchView (int caseNr)
Switch to another view (case).
Public Member Functions
Window ()
Constructor.
~Window ()=default
Destructor.
void AddCase (const std::string &caseName, const std::string &dir, int nrOfRuns=100)
Add a case to the window.
void Finish ()
Private Member Functions
void CreateActions ()
Create the menu actions.
void BuildBoxPlot (const QString &title, std::vector< int > &values)
Build and show a boxplot.
qreal FindMedian (const std::vector< int > &list, int begin, int end)
Get the median value within a range.
Private Attributes
std::ofstream results
QToolBar * toolbar
int currentView
std::vector< QChart * > charts
std::vector< QChartView * > chartViews
List of all the chart views (cases).
QStackedWidget * stack
Detailed Description
The main window in the qttool program.
Definition at line 39 of file ool/Window.h.
Constructor & Destructor Documentation
Window()
stride::qttool::Window::Window ()
Constructor.
Definition at line 9 of file ool/Window.cpp.
References CreateActions(), and results.
~Window()
stride::qttool::Window::~Window () default
Destructor.
Member Function Documentation
AddCase()
void stride::qttool::Window::AddCase (const std::string & caseName, const std::string & dir, int nrOfRuns = 100)
Add a case to the window.
Example of a case: Influenza
Parameters
caseName Name of the case.
dir Path to the dir that contains all the data (i.e. dirs of the rng type that contains the results of a simulation)
nrOfRuns Number of runs for each rng type.
Definition at line 16 of file ool/Window.cpp.
References BuildBoxPlot(), charts, chartViews, currentView, results, stack, SwitchView(), toolbar, and stride::ContactLogMode::ToString().
Referenced by main().
Finish()
void stride::qttool::Window::Finish ()
Definition at line 92 of file ool/Window.cpp.
References results, and stack.
Referenced by main().
Save
void stride::qttool::Window::Save () slot
Save the current display to a file.
Definition at line 99 of file ool/Window.cpp.
References chartViews, stride::util::FileSys::GetCurrentDir(), and stack.
Referenced by CreateActions().
SwitchView
void stride::qttool::Window::SwitchView (int caseNr) slot
Switch to another view (case).
Definition at line 112 of file ool/Window.cpp.
References stack.
Referenced by AddCase().
CreateActions()
void stride::qttool::Window::CreateActions () private
Create the menu actions.
Definition at line 118 of file ool/Window.cpp.
References Save().
Referenced by Window().
BuildBoxPlot()
void stride::qttool::Window::BuildBoxPlot (const QString & title, std::vector< int > & values) private
Build and show a boxplot.
Parameters
title Title of the boxplot.
values All the values used for the boxplot, list will be sorted afterwards.
Definition at line 124 of file ool/Window.cpp.
References charts, currentView, FindMedian(), and results.
Referenced by AddCase().
FindMedian()
qreal stride::qttool::Window::FindMedian (const std::vector< int > & list, int begin, int end) private
Get the median value within a range.
source: https://doc.qt.io/qt-5.10/qtcharts-boxplotchart-boxdatareader-cpp.html
Parameters
list The sorted list.
begin The start of the range.
end The end of the range.
Returns
The median.
Definition at line 156 of file ool/Window.cpp.
Referenced by BuildBoxPlot().
Member Data Documentation
results
std::ofstream stride::qttool::Window::results private
Definition at line 84 of file ool/Window.h.
Referenced by AddCase(), BuildBoxPlot(), Finish(), and Window().
toolbar
QToolBar* stride::qttool::Window::toolbar private
Definition at line 86 of file ool/Window.h.
Referenced by AddCase().
currentView
int stride::qttool::Window::currentView private
Definition at line 88 of file ool/Window.h.
Referenced by AddCase(), and BuildBoxPlot().
charts
std::vector<QChart*> stride::qttool::Window::charts private
Definition at line 89 of file ool/Window.h.
Referenced by AddCase(), and BuildBoxPlot().
chartViews
std::vector<QChartView*> stride::qttool::Window::chartViews private
List of all the chart views (cases).
Definition at line 90 of file ool/Window.h.
Referenced by AddCase(), and Save().
stack
QStackedWidget* stride::qttool::Window::stack private
Definition at line 91 of file ool/Window.h.
Referenced by AddCase(), Finish(), Save(), and SwitchView().
The documentation for this class was generated from the following files:
ool/Window.h
ool/Window.cpp