Stride Reference Manual: stride::GuiController Class Reference
stride::GuiController Class Reference
#include <GuiController.h>
Public Member Functions
GuiController (const boost::property_tree::ptree &config_pt)
Straight initialization.
void Control () override
Actual run of the simulator.
Public Member Functions inherited from stride::CliController
CliController (const boost::property_tree::ptree &configPt)
Straight initialization.
void GeneratePopulation ()
Generate population, write to output file.
Private Member Functions
void RegisterQtViewers (std::shared_ptr< GuiRunner > runner) override
Register the viewers of the SimRunner.
Additional Inherited Members
Protected Member Functions inherited from stride::CliController
CliController ()
Empty controller: used as target for delegation.
void CheckEnv ()
Check install environment.
void CheckOutputPrefix ()
void LogSetup ()
Logs info on setup for cli environment to stride_logger.
void MakeLogger ()
Make the appropriate logger for cli environment and register as stride_logger.
void RegisterViewers (std::shared_ptr< SimRunner > runner)
Register the viewers of the SimRunner.
Protected Attributes inherited from stride::CliController
boost::property_tree::ptree m_config_pt
Main configuration for run and sim.
std::string m_output_prefix
Prefix to output (name prefix or prefix dir)
util::Stopwatch m_run_clock
Stopwatch for timing the computation.
std::shared_ptr< spdlog::logger > m_stride_logger
General logger.
bool m_use_install_dirs
int argc
Working dir or install dir mode.
char ** argv
= {nullptr}
QApplication app
The QT application.
Detailed Description
Definition at line 24 of file GuiController.h.
Constructor & Destructor Documentation
GuiController()
stride::GuiController::GuiController (const boost::property_tree::ptree & config_pt)
Straight initialization.
Definition at line 11 of file GuiController.cpp.
Member Function Documentation
Control()
void stride::GuiController::Control () override virtual
Actual run of the simulator.
Reimplemented from stride::CliController.
Definition at line 13 of file GuiController.cpp.
References stride::CliController::app, stride::CliController::m_stride_logger, RegisterQtViewers(), and stride::CliController::RegisterViewers().
Referenced by main().
RegisterQtViewers()
void stride::GuiController::RegisterQtViewers (std::shared_ptr< GuiRunner > runner) override private virtual
Register the viewers of the SimRunner.
Reimplemented from stride::CliController.
Definition at line 30 of file GuiController.cpp.
References stride::CliController::m_config_pt, stride::CliController::m_stride_logger, and stride::viewers::MapViewer::Update().
Referenced by Control().
The documentation for this class was generated from the following files:
GuiController.h
GuiController.cpp