Stride Reference Manual: stride::Person Class Reference
stride::Person Class Reference
Store and handle person data.
#include <Person.h>
Public Member Functions
Person ()
Default construction (for population vector).
Person (unsigned int id, double age, unsigned int householdId, unsigned int schoolId, unsigned int workId, unsigned int primaryCommunityId, unsigned int secondaryCommunityId)
Constructor: set the person data.
bool operator!= (const Person &p) const
Is this person not equal to the given person?
double GetAge () const
Get the age.
Belief * GetBelief ()
Return belief info.
const Belief * GetBelief () const
Return belief info.
unsigned int GetPoolId (const ContactPoolType::Id &poolType) const
Get ID of contactpool_type.
char GetGender () const
Return person's gender.
Health & GetHealth ()
Return person's health status.
const Health & GetHealth () const
Return person's health status.
unsigned int GetId () const
Get the id.
bool IsInPool (const ContactPoolType::Id &poolType) const
Check if a person is present today in a given contactpool.
bool IsSurveyParticipant () const
Does this person participates in the social contact study?
void ParticipateInSurvey ()
Participate in social contact study and log person details.
void Travel ()
Initiate Travel.
void SetBelief (Belief *belief)
Set the beliefs. Pointer into Population's beliefcontainer.
void Update (bool isWorkOff, bool isSchoolOff)
Update the health status and presence in contactpools.
void Update (bool isWorkOff, bool isSchoolOff, std::shared_ptr< stride::TravelTable > table, const size_t index)
Update the health status and presence in contactpools and handle travel of persons.
void Update (Person *p)
Private Attributes
double m_age
The age.
Belief * m_belief
Health beliefs related data (raw pointer intentional).
char m_gender
Health m_health
Health info for this person.
unsigned int m_id
The id.
bool m_is_participant
Is participating in the social contact study.
bool m_is_traveling
Is traveling to another pop.
ContactPoolType::Id m_travel_pool_type
Ids (school, work, etc) of pools you belong to Id value 0 means you do not belong to any pool of that type (e.g.
ContactPoolType::IdSubscriptArray< unsigned int > m_pool_ids
Is person present/absent in pools of each of the types (school, work, etc)?
ContactPoolType::IdSubscriptArray< bool > m_in_pools
Detailed Description
Store and handle person data.
Definition at line 36 of file Person.h.
Constructor & Destructor Documentation
Person() [1/2]
stride::Person::Person () inline
Default construction (for population vector).
Definition at line 40 of file Person.h.
Person() [2/2]
stride::Person::Person (unsigned int id, double age, unsigned int householdId, unsigned int schoolId, unsigned int workId, unsigned int primaryCommunityId, unsigned int secondaryCommunityId) inline
Constructor: set the person data.
Definition at line 47 of file Person.h.
Member Function Documentation
operator!=()
bool stride::Person::operator!= (const Person & p) const inline
Is this person not equal to the given person?
Definition at line 57 of file Person.h.
References m_id.
GetAge()
double stride::Person::GetAge () const inline
Get the age.
Definition at line 60 of file Person.h.
References m_age.
Referenced by stride::Immunizer::Random(), stride::SurveySeeder::Seed(), and stride::DiseaseSeeder::Seed().
GetBelief() [1/2]
Belief* stride::Person::GetBelief () inline
Return belief info.
Definition at line 63 of file Person.h.
References m_belief.
GetBelief() [2/2]
const Belief* stride::Person::GetBelief () const inline
Return belief info.
Definition at line 66 of file Person.h.
References m_belief.
GetPoolId()
unsigned int stride::Person::GetPoolId (const ContactPoolType::Id & poolType) const inline
Get ID of contactpool_type.
Definition at line 69 of file Person.h.
References m_pool_ids.
Referenced by stride::SurveySeeder::Seed().
GetGender()
char stride::Person::GetGender () const inline
Return person's gender.
Definition at line 72 of file Person.h.
References m_gender.
Referenced by stride::SurveySeeder::Seed().
GetHealth() [1/2]
Health& stride::Person::GetHealth () inline
Return person's health status.
Definition at line 75 of file Person.h.
References m_health.
Referenced by stride::Infector< LL, TIC, LIP, TO >::Exec(), stride::Infector< LL, TIC, NoLocalInformation, true >::Exec(), stride::Immunizer::Random(), and stride::DiseaseSeeder::Seed().
GetHealth() [2/2]
const Health& stride::Person::GetHealth () const inline
Return person's health status.
Definition at line 78 of file Person.h.
References m_health.
GetId()
unsigned int stride::Person::GetId () const inline
Get the id.
Definition at line 81 of file Person.h.
References m_id.
Referenced by stride::SurveySeeder::Seed(), and stride::DiseaseSeeder::Seed().
IsInPool()
bool stride::Person::IsInPool (const ContactPoolType::Id & poolType) const inline
Check if a person is present today in a given contactpool.
Definition at line 84 of file Person.h.
References m_in_pools.
Referenced by stride::Infector< LL, TIC, LIP, TO >::Exec(), and stride::Infector< LL, TIC, NoLocalInformation, true >::Exec().
IsSurveyParticipant()
bool stride::Person::IsSurveyParticipant () const inline
Does this person participates in the social contact study?
Definition at line 87 of file Person.h.
References m_is_participant.
Referenced by stride::SurveySeeder::Seed().
ParticipateInSurvey()
void stride::Person::ParticipateInSurvey () inline
Participate in social contact study and log person details.
Definition at line 90 of file Person.h.
References m_is_participant.
Referenced by stride::SurveySeeder::Seed().
Travel()
void stride::Person::Travel () inline
Initiate Travel.
Definition at line 93 of file Person.h.
References m_is_traveling.
SetBelief()
void stride::Person::SetBelief (Belief * belief) inline
Set the beliefs. Pointer into Population's beliefcontainer.
Definition at line 96 of file Person.h.
References m_belief.
Update() [1/3]
void stride::Person::Update (bool isWorkOff, bool isSchoolOff)
Update the health status and presence in contactpools.
Definition at line 29 of file Person.cpp.
References stride::MinAdultAge().
Update() [2/3]
void stride::Person::Update (bool isWorkOff, bool isSchoolOff, std::shared_ptr< stride::TravelTable > table, const size_t index)
Update the health status and presence in contactpools and handle travel of persons.
Definition at line 52 of file Person.cpp.
References stride::MinAdultAge().
Update() [3/3]
void stride::Person::Update (Person * p)
Definition at line 95 of file Person.cpp.
Member Data Documentation
m_age
double stride::Person::m_age private
The age.
Definition at line 108 of file Person.h.
Referenced by GetAge().
m_belief
Belief* stride::Person::m_belief private
Health beliefs related data (raw pointer intentional).
Definition at line 109 of file Person.h.
Referenced by GetBelief(), and SetBelief().
m_gender
char stride::Person::m_gender private
Definition at line 110 of file Person.h.
Referenced by GetGender().
m_health
Health stride::Person::m_health private
Health info for this person.
Definition at line 111 of file Person.h.
Referenced by GetHealth().
m_id
unsigned int stride::Person::m_id private
The id.
Definition at line 112 of file Person.h.
Referenced by GetId(), and operator!=().
m_is_participant
bool stride::Person::m_is_participant private
Is participating in the social contact study.
Definition at line 113 of file Person.h.
Referenced by IsSurveyParticipant(), and ParticipateInSurvey().
m_is_traveling
bool stride::Person::m_is_traveling private
Is traveling to another pop.
Definition at line 114 of file Person.h.
Referenced by stride::TravelTable::Travel(), and Travel().
m_travel_pool_type
ContactPoolType::Id stride::Person::m_travel_pool_type private
Ids (school, work, etc) of pools you belong to Id value 0 means you do not belong to any pool of that type (e.g.
school and work are mutually exclusive.
Definition at line 115 of file Person.h.
Referenced by stride::TravelTable::Travel().
m_pool_ids
ContactPoolType::IdSubscriptArray<unsigned int> stride::Person::m_pool_ids private
Is person present/absent in pools of each of the types (school, work, etc)?
Definition at line 119 of file Person.h.
Referenced by GetPoolId(), stride::TravelTable::Travel(), and stride::TravelTable::Update().
m_in_pools
ContactPoolType::IdSubscriptArray<bool> stride::Person::m_in_pools private
Definition at line 122 of file Person.h.
Referenced by IsInPool().
The documentation for this class was generated from the following files:
Person.h
Person.cpp