Stride Reference Manual: stride::qt::MapBuilder Class Reference
stride::qt::MapBuilder Class Reference
Builder class that builds a stride::qt::Map.
#include <MapBuilder.h>
Public Member Functions
MapBuilder ()=default
Default constructor.
~MapBuilder ()=default
Default destructor.
std::shared_ptr< stride::qt::Map > BuildMap (const stride::qt::Window *window, std::shared_ptr< stride::GeoGrid > geoGrid, double vaccineRate=1.0) const
Build a stride::qt::Map.
Detailed Description
Builder class that builds a stride::qt::Map.
Definition at line 17 of file MapBuilder.h.
Constructor & Destructor Documentation
MapBuilder()
stride::qt::MapBuilder::MapBuilder () default
Default constructor.
~MapBuilder()
stride::qt::MapBuilder::~MapBuilder () default
Default destructor.
Member Function Documentation
BuildMap()
std::shared_ptr< stride::qt::Map > stride::qt::MapBuilder::BuildMap (const stride::qt::Window * window, std::shared_ptr< stride::GeoGrid > geoGrid, double vaccineRate = 1.0) const
Build a stride::qt::Map.
Parameters
window The window for which the map serves (need the map image size to make correct translations).
geoGrid The geo grid that needs to be converted to a map.
vaccineRate The vaccine rate which is used during the simulation [optional: default = 1.0].
Returns
The newly created map.
Definition at line 6 of file MapBuilder.cpp.
References stride::qt::Window::ConvertLatLongToPixel(), stride::Point2D::GetX(), and stride::Point2D::GetY().
The documentation for this class was generated from the following files:
MapBuilder.h
MapBuilder.cpp