Stride Reference Manual: stride::util::CSV Class Reference
stride::util::CSV Class Reference
A collection of CSVRow elements.
#include <CSV.h>
Public Member Functions
CSV (const boost::filesystem::path &path, std::initializer_list< std::string > optLabels={})
Initialize from file.
CSV (std::initializer_list< std::string > labels)
Initialize with header.
CSV ()=default
Default constructor. Mainly used for swig.
bool operator== (const CSV &other) const
Compare operator.
template<typename... T>
void AddRow (const T &... values)
Add row of values. Will all be converted to string with StringUtils::ToString.
void AddRow (std::vector< std::string > values)
Add row of string values.
size_t GetColumnCount () const
Amount of columns in the CSV.
size_t GetIndexForLabel (const std::string &label) const
Convert label to index for more user friendly and robuust implementation.
void Write (const boost::filesystem::path &path) const
Write CSV to file.
std::vector< std::string > GetLabels () const
Protected Attributes
std::vector< std::string > labels
size_t columnCount = 0
Detailed Description
A collection of CSVRow elements.
Iterate with begin and end like STL containers.
Definition at line 37 of file CSV.h.
Constructor & Destructor Documentation
CSV() [1/3]
stride::util::CSV::CSV (const boost::filesystem::path & path, std::initializer_list< std::string > optLabels = {}) explicit
Initialize from file.
If optLabels not specied, the file is required. Otherwise initialize like second constructor.
CSV() [2/3]
stride::util::CSV::CSV (std::initializer_list< std::string > labels)
Initialize with header.
CSV() [3/3]
stride::util::CSV::CSV () default
Default constructor. Mainly used for swig.
Member Function Documentation
operator==()
bool stride::util::CSV::operator== (const CSV & other) const
Compare operator.
Definition at line 93 of file CSV.cpp.
References labels.
AddRow() [1/2]
template<typename... T> void stride::util::CSV::AddRow (const T &... values) inline
Add row of values. Will all be converted to string with StringUtils::ToString.
Definition at line 85 of file CSV.h.
References stride::util::ToString().
AddRow() [2/2]
void stride::util::CSV::AddRow (std::vector< std::string > values)
Add row of string values.
Definition at line 98 of file CSV.cpp.
GetColumnCount()
size_t stride::util::CSV::GetColumnCount () const inline
Amount of columns in the CSV.
Definition at line 66 of file CSV.h.
References columnCount.
Referenced by stride::util::CSVRow::CSVRow().
GetIndexForLabel()
size_t stride::util::CSV::GetIndexForLabel (const std::string & label) const
Convert label to index for more user friendly and robuust implementation.
This level of indirection does introduce a perfomance tradeoff.
Definition at line 104 of file CSV.cpp.
References labels.
Referenced by stride::FillLocationAttribute().
Write()
void stride::util::CSV::Write (const boost::filesystem::path & path) const
Write CSV to file.
Definition at line 113 of file CSV.cpp.
References labels.
GetLabels()
std::vector< std::string > stride::util::CSV::GetLabels () const
Definition at line 137 of file CSV.cpp.
References labels.
Referenced by stride::GeoGridBuilder::ReadCommuting().
Member Data Documentation
labels
std::vector<std::string> stride::util::CSV::labels protected
Definition at line 80 of file CSV.h.
Referenced by GetIndexForLabel(), GetLabels(), operator==(), and Write().
columnCount
size_t stride::util::CSV::columnCount = 0 protected
Definition at line 81 of file CSV.h.
Referenced by GetColumnCount().
The documentation for this class was generated from the following files:
CSV.h
CSV.cpp