Stride Reference Manual: main.cpp File Reference
qt/main.cpp File Reference
#include "pop/Population.h"
#include "qt/QSim.h"
#include <tclap/CmdLine.h>
#include <QApplication>
Functions
int main (int argc, char **argv)
Main program of the stridepostpr simulator. (postprocessor)
Function Documentation
main()
int main (int argc, char ** argv)
Main program of the stridepostpr simulator. (postprocessor)
Definition at line 8 of file qt/main.cpp.
References stride::Population::Create(), stride::Population::CreateEmpty(), stride::qt::QSim::Exec(), stride::util::FileSys::GetCurrentDir(), and stride::qt::QSim::LoadLog().