Stride Reference Manual: stride::CliController Class Reference
stride::CliController Class Reference
Controls a simulation run initiated with the command line interface (cli).
#include <CliController.h>
Public Member Functions
CliController (const boost::property_tree::ptree &configPt)
Straight initialization.
virtual void Control ()
Actual run of the simulator.
void GeneratePopulation ()
Generate population, write to output file.
Protected Member Functions
CliController ()
Empty controller: used as target for delegation.
void CheckEnv ()
Check install environment.
void CheckOutputPrefix ()
void LogSetup ()
Logs info on setup for cli environment to stride_logger.
void MakeLogger ()
Make the appropriate logger for cli environment and register as stride_logger.
void RegisterViewers (std::shared_ptr< SimRunner > runner)
Register the viewers of the SimRunner.
virtual void RegisterQtViewers (std::shared_ptr< GuiRunner > runner)
Register the qt viewers of the GuiRunner.
Protected Attributes
boost::property_tree::ptree m_config_pt
Main configuration for run and sim.
std::string m_output_prefix
Prefix to output (name prefix or prefix dir)
util::Stopwatch m_run_clock
Stopwatch for timing the computation.
std::shared_ptr< spdlog::logger > m_stride_logger
General logger.
bool m_use_install_dirs
int argc
Working dir or install dir mode.
char ** argv
= {nullptr}
QApplication app
The QT application.
Detailed Description
Controls a simulation run initiated with the command line interface (cli).
CliController functions include:
accepts the commandline arguments
checks the OpenMP environment
checks the file system environment
reads the config file specified on the cli
effects cli overrides of config parameters
patches the config file for any remaining defaults
interprets and executes the output prefix
makes a stride logger The CliController execution
creates a simulation runner (
See Also
SimRunner)
registers the appropriate viewers
runs the simulation
Definition at line 49 of file CliController.h.
Constructor & Destructor Documentation
stride::CliController::CliController (const boost::property_tree::ptree & configPt) explicit
Straight initialization.
stride::CliController::CliController () explicit protected
Empty controller: used as target for delegation.
Definition at line 51 of file CliController.cpp.
Member Function Documentation
void stride::CliController::Control () virtual
Actual run of the simulator.
Reimplemented in stride::GuiController.
Definition at line 95 of file CliController.cpp.
References app, stride::Population::Create(), stride::Population::CreateEmpty(), m_config_pt, m_stride_logger, RegisterQtViewers(), and RegisterViewers().
Referenced by main().
void stride::CliController::GeneratePopulation ()
Generate population, write to output file.
Definition at line 144 of file CliController.cpp.
References stride::Population::Create(), and m_config_pt.
Referenced by main().
void stride::CliController::CheckEnv () protected
Check install environment.
Definition at line 73 of file CliController.cpp.
References stride::util::FileSys::CheckInstallEnv(), and m_use_install_dirs.
void stride::CliController::CheckOutputPrefix () protected
Definition at line 83 of file CliController.cpp.
References stride::util::FileSys::IsDirectoryString(), and m_output_prefix.
void stride::CliController::LogSetup () protected
Logs info on setup for cli environment to stride_logger.
Definition at line 211 of file CliController.cpp.
References stride::util::FileSys::GetConfigDir(), stride::util::FileSys::GetCurrentDir(), stride::util::FileSys::GetDataDir(), stride::util::FileSys::GetExecPath(), stride::util::FileSys::GetRootDir(), stride::util::ConfigInfo::GitRevision(), stride::util::ConfigInfo::HaveOpenMP(), m_config_pt, m_output_prefix, m_stride_logger, m_use_install_dirs, stride::util::ConfigInfo::NumberAvailableThreads(), and stride::ContactLogMode::ToString().
void stride::CliController::MakeLogger () protected
Make the appropriate logger for cli environment and register as stride_logger.
Definition at line 152 of file CliController.cpp.
References stride::util::FileSys::BuildPath(), stride::util::LogUtils::CreateCliLogger(), m_config_pt, m_output_prefix, and m_stride_logger.
void stride::CliController::RegisterViewers (std::shared_ptr< SimRunner > runner) protected
Register the viewers of the SimRunner.
Definition at line 161 of file CliController.cpp.
References m_config_pt, m_output_prefix, m_stride_logger, stride::viewers::CliViewer::Update(), stride::viewers::AdoptedViewer::Update(), stride::viewers::SummaryViewer::Update(), stride::viewers::PersonsViewer::Update(), and stride::viewers::InfectedViewer::Update().
Referenced by stride::GuiController::Control(), and Control().
void stride::CliController::RegisterQtViewers (std::shared_ptr< GuiRunner > runner) protected virtual
Register the qt viewers of the GuiRunner.
Reimplemented in stride::GuiController.
Definition at line 197 of file CliController.cpp.
References m_config_pt, m_stride_logger, and stride::viewers::MapViewer::Update().
Referenced by Control().
Member Data Documentation
boost::property_tree::ptree stride::CliController::m_config_pt protected
Main configuration for run and sim.
Definition at line 86 of file CliController.h.
Referenced by Control(), GeneratePopulation(), LogSetup(), MakeLogger(), stride::GuiController::RegisterQtViewers(), RegisterQtViewers(), and RegisterViewers().
std::string stride::CliController::m_output_prefix protected
Prefix to output (name prefix or prefix dir)
Definition at line 87 of file CliController.h.
Referenced by CheckOutputPrefix(), LogSetup(), MakeLogger(), and RegisterViewers().
util::Stopwatch stride::CliController::m_run_clock protected
Stopwatch for timing the computation.
Definition at line 88 of file CliController.h.
std::shared_ptr<spdlog::logger> stride::CliController::m_stride_logger protected
General logger.
Definition at line 89 of file CliController.h.
Referenced by stride::GuiController::Control(), Control(), LogSetup(), MakeLogger(), stride::GuiController::RegisterQtViewers(), RegisterQtViewers(), and RegisterViewers().
bool stride::CliController::m_use_install_dirs protected
Definition at line 90 of file CliController.h.
Referenced by CheckEnv(), and LogSetup().
int stride::CliController::argc protected
Working dir or install dir mode.
= 1
Definition at line 93 of file CliController.h.
char** stride::CliController::argv protected
= {nullptr}
Definition at line 94 of file CliController.h.
QApplication stride::CliController::app protected
The QT application.
Definition at line 95 of file CliController.h.
Referenced by stride::GuiController::Control(), and Control().
The documentation for this class was generated from the following files:
CliController.h
CliController.cpp